// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bigtwo_logic_msg.proto

package net

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// 游戏信息
type MsgBigtwoGameInfoResp struct {
	CurUser          *uint32  `protobuf:"varint,1,opt,name=cur_user" json:"cur_user,omitempty"`
	TurnWiner        *uint32  `protobuf:"varint,2,opt,name=turn_winer" json:"turn_winer,omitempty"`
	FirstUser        *uint32  `protobuf:"varint,3,opt,name=first_user" json:"first_user,omitempty"`
	TurnCardData     []uint32 `protobuf:"varint,4,rep,name=turn_card_data" json:"turn_card_data,omitempty"`
	HandCardCount    []uint32 `protobuf:"varint,5,rep,name=hand_card_count" json:"hand_card_count,omitempty"`
	HandCardData     []uint32 `protobuf:"varint,6,rep,name=hand_card_data" json:"hand_card_data,omitempty"`
	GameState        *uint32  `protobuf:"varint,7,opt,name=game_state" json:"game_state,omitempty"`
	WaitTime         *uint32  `protobuf:"varint,8,opt,name=wait_time" json:"wait_time,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *MsgBigtwoGameInfoResp) Reset()                    { *m = MsgBigtwoGameInfoResp{} }
func (m *MsgBigtwoGameInfoResp) String() string            { return proto.CompactTextString(m) }
func (*MsgBigtwoGameInfoResp) ProtoMessage()               {}
func (*MsgBigtwoGameInfoResp) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

func (m *MsgBigtwoGameInfoResp) GetCurUser() uint32 {
	if m != nil && m.CurUser != nil {
		return *m.CurUser
	}
	return 0
}

func (m *MsgBigtwoGameInfoResp) GetTurnWiner() uint32 {
	if m != nil && m.TurnWiner != nil {
		return *m.TurnWiner
	}
	return 0
}

func (m *MsgBigtwoGameInfoResp) GetFirstUser() uint32 {
	if m != nil && m.FirstUser != nil {
		return *m.FirstUser
	}
	return 0
}

func (m *MsgBigtwoGameInfoResp) GetTurnCardData() []uint32 {
	if m != nil {
		return m.TurnCardData
	}
	return nil
}

func (m *MsgBigtwoGameInfoResp) GetHandCardCount() []uint32 {
	if m != nil {
		return m.HandCardCount
	}
	return nil
}

func (m *MsgBigtwoGameInfoResp) GetHandCardData() []uint32 {
	if m != nil {
		return m.HandCardData
	}
	return nil
}

func (m *MsgBigtwoGameInfoResp) GetGameState() uint32 {
	if m != nil && m.GameState != nil {
		return *m.GameState
	}
	return 0
}

func (m *MsgBigtwoGameInfoResp) GetWaitTime() uint32 {
	if m != nil && m.WaitTime != nil {
		return *m.WaitTime
	}
	return 0
}

// 游戏开始
type MsgBigtwoStartResp struct {
	StartUser        *uint32  `protobuf:"varint,1,opt,name=start_user" json:"start_user,omitempty"`
	HandCardData     []uint32 `protobuf:"varint,6,rep,name=hand_card_data" json:"hand_card_data,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *MsgBigtwoStartResp) Reset()                    { *m = MsgBigtwoStartResp{} }
func (m *MsgBigtwoStartResp) String() string            { return proto.CompactTextString(m) }
func (*MsgBigtwoStartResp) ProtoMessage()               {}
func (*MsgBigtwoStartResp) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

func (m *MsgBigtwoStartResp) GetStartUser() uint32 {
	if m != nil && m.StartUser != nil {
		return *m.StartUser
	}
	return 0
}

func (m *MsgBigtwoStartResp) GetHandCardData() []uint32 {
	if m != nil {
		return m.HandCardData
	}
	return nil
}

// 玩家出牌
type MsgBigtwoOutCardReq struct {
	CardData         []uint32 `protobuf:"varint,1,rep,name=card_data" json:"card_data,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *MsgBigtwoOutCardReq) Reset()                    { *m = MsgBigtwoOutCardReq{} }
func (m *MsgBigtwoOutCardReq) String() string            { return proto.CompactTextString(m) }
func (*MsgBigtwoOutCardReq) ProtoMessage()               {}
func (*MsgBigtwoOutCardReq) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{2} }

func (m *MsgBigtwoOutCardReq) GetCardData() []uint32 {
	if m != nil {
		return m.CardData
	}
	return nil
}

// 玩家出牌返回
type MsgBigtwoOutCardResp struct {
	CurUser          *uint32  `protobuf:"varint,1,opt,name=cur_user" json:"cur_user,omitempty"`
	OutCardUser      *uint32  `protobuf:"varint,2,opt,name=out_card_user" json:"out_card_user,omitempty"`
	CardData         []uint32 `protobuf:"varint,3,rep,name=card_data" json:"card_data,omitempty"`
	RetCode          *uint32  `protobuf:"varint,4,opt,name=ret_code" json:"ret_code,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *MsgBigtwoOutCardResp) Reset()                    { *m = MsgBigtwoOutCardResp{} }
func (m *MsgBigtwoOutCardResp) String() string            { return proto.CompactTextString(m) }
func (*MsgBigtwoOutCardResp) ProtoMessage()               {}
func (*MsgBigtwoOutCardResp) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{3} }

func (m *MsgBigtwoOutCardResp) GetCurUser() uint32 {
	if m != nil && m.CurUser != nil {
		return *m.CurUser
	}
	return 0
}

func (m *MsgBigtwoOutCardResp) GetOutCardUser() uint32 {
	if m != nil && m.OutCardUser != nil {
		return *m.OutCardUser
	}
	return 0
}

func (m *MsgBigtwoOutCardResp) GetCardData() []uint32 {
	if m != nil {
		return m.CardData
	}
	return nil
}

func (m *MsgBigtwoOutCardResp) GetRetCode() uint32 {
	if m != nil && m.RetCode != nil {
		return *m.RetCode
	}
	return 0
}

// pass
type MsgBigtwoPassCardReq struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgBigtwoPassCardReq) Reset()                    { *m = MsgBigtwoPassCardReq{} }
func (m *MsgBigtwoPassCardReq) String() string            { return proto.CompactTextString(m) }
func (*MsgBigtwoPassCardReq) ProtoMessage()               {}
func (*MsgBigtwoPassCardReq) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{4} }

// pass返回
type MsgBigtwoPassCardResp struct {
	TurnOver         *uint32 `protobuf:"varint,1,opt,name=turn_over" json:"turn_over,omitempty"`
	CurUser          *uint32 `protobuf:"varint,2,opt,name=cur_user" json:"cur_user,omitempty"`
	PassCardUser     *uint32 `protobuf:"varint,3,opt,name=pass_card_user" json:"pass_card_user,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgBigtwoPassCardResp) Reset()                    { *m = MsgBigtwoPassCardResp{} }
func (m *MsgBigtwoPassCardResp) String() string            { return proto.CompactTextString(m) }
func (*MsgBigtwoPassCardResp) ProtoMessage()               {}
func (*MsgBigtwoPassCardResp) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{5} }

func (m *MsgBigtwoPassCardResp) GetTurnOver() uint32 {
	if m != nil && m.TurnOver != nil {
		return *m.TurnOver
	}
	return 0
}

func (m *MsgBigtwoPassCardResp) GetCurUser() uint32 {
	if m != nil && m.CurUser != nil {
		return *m.CurUser
	}
	return 0
}

func (m *MsgBigtwoPassCardResp) GetPassCardUser() uint32 {
	if m != nil && m.PassCardUser != nil {
		return *m.PassCardUser
	}
	return 0
}

// 请求手牌
type MsgBigtwoHandCardReq struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgBigtwoHandCardReq) Reset()                    { *m = MsgBigtwoHandCardReq{} }
func (m *MsgBigtwoHandCardReq) String() string            { return proto.CompactTextString(m) }
func (*MsgBigtwoHandCardReq) ProtoMessage()               {}
func (*MsgBigtwoHandCardReq) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{6} }

// 返回手牌
type MsgBigtwoHandCardResp struct {
	ChairId          *uint32  `protobuf:"varint,1,opt,name=chair_id" json:"chair_id,omitempty"`
	CardData         []uint32 `protobuf:"varint,2,rep,name=card_data" json:"card_data,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *MsgBigtwoHandCardResp) Reset()                    { *m = MsgBigtwoHandCardResp{} }
func (m *MsgBigtwoHandCardResp) String() string            { return proto.CompactTextString(m) }
func (*MsgBigtwoHandCardResp) ProtoMessage()               {}
func (*MsgBigtwoHandCardResp) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{7} }

func (m *MsgBigtwoHandCardResp) GetChairId() uint32 {
	if m != nil && m.ChairId != nil {
		return *m.ChairId
	}
	return 0
}

func (m *MsgBigtwoHandCardResp) GetCardData() []uint32 {
	if m != nil {
		return m.CardData
	}
	return nil
}

// 游戏结束
type MsgBigtwoGameOverNotify struct {
	Winscores        []int64     `protobuf:"varint,1,rep,name=winscores" json:"winscores,omitempty"`
	WinCardNums      []int32     `protobuf:"varint,2,rep,name=winCardNums" json:"winCardNums,omitempty"`
	AllWinCardNums   []*MsgCards `protobuf:"bytes,3,rep,name=allWinCardNums" json:"allWinCardNums,omitempty"`
	LeftCardData     []*MsgCards `protobuf:"bytes,4,rep,name=left_card_data" json:"left_card_data,omitempty"`
	AllCardData      []*MsgCards `protobuf:"bytes,5,rep,name=all_card_data" json:"all_card_data,omitempty"`
	HasPayAll        *int32      `protobuf:"varint,6,opt,name=hasPayAll" json:"hasPayAll,omitempty"`
	PayAllUser       *int32      `protobuf:"varint,7,opt,name=payAllUser" json:"payAllUser,omitempty"`
	BaseWinscores    []int64     `protobuf:"varint,8,rep,name=base_winscores" json:"base_winscores,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *MsgBigtwoGameOverNotify) Reset()                    { *m = MsgBigtwoGameOverNotify{} }
func (m *MsgBigtwoGameOverNotify) String() string            { return proto.CompactTextString(m) }
func (*MsgBigtwoGameOverNotify) ProtoMessage()               {}
func (*MsgBigtwoGameOverNotify) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{8} }

func (m *MsgBigtwoGameOverNotify) GetWinscores() []int64 {
	if m != nil {
		return m.Winscores
	}
	return nil
}

func (m *MsgBigtwoGameOverNotify) GetWinCardNums() []int32 {
	if m != nil {
		return m.WinCardNums
	}
	return nil
}

func (m *MsgBigtwoGameOverNotify) GetAllWinCardNums() []*MsgCards {
	if m != nil {
		return m.AllWinCardNums
	}
	return nil
}

func (m *MsgBigtwoGameOverNotify) GetLeftCardData() []*MsgCards {
	if m != nil {
		return m.LeftCardData
	}
	return nil
}

func (m *MsgBigtwoGameOverNotify) GetAllCardData() []*MsgCards {
	if m != nil {
		return m.AllCardData
	}
	return nil
}

func (m *MsgBigtwoGameOverNotify) GetHasPayAll() int32 {
	if m != nil && m.HasPayAll != nil {
		return *m.HasPayAll
	}
	return 0
}

func (m *MsgBigtwoGameOverNotify) GetPayAllUser() int32 {
	if m != nil && m.PayAllUser != nil {
		return *m.PayAllUser
	}
	return 0
}

func (m *MsgBigtwoGameOverNotify) GetBaseWinscores() []int64 {
	if m != nil {
		return m.BaseWinscores
	}
	return nil
}

func init() {
	proto.RegisterType((*MsgBigtwoGameInfoResp)(nil), "net.msg_bigtwo_game_info_resp")
	proto.RegisterType((*MsgBigtwoStartResp)(nil), "net.msg_bigtwo_start_resp")
	proto.RegisterType((*MsgBigtwoOutCardReq)(nil), "net.msg_bigtwo_out_card_req")
	proto.RegisterType((*MsgBigtwoOutCardResp)(nil), "net.msg_bigtwo_out_card_resp")
	proto.RegisterType((*MsgBigtwoPassCardReq)(nil), "net.msg_bigtwo_pass_card_req")
	proto.RegisterType((*MsgBigtwoPassCardResp)(nil), "net.msg_bigtwo_pass_card_resp")
	proto.RegisterType((*MsgBigtwoHandCardReq)(nil), "net.msg_bigtwo_hand_card_req")
	proto.RegisterType((*MsgBigtwoHandCardResp)(nil), "net.msg_bigtwo_hand_card_resp")
	proto.RegisterType((*MsgBigtwoGameOverNotify)(nil), "net.msg_bigtwo_game_over_notify")
}

func init() { proto.RegisterFile("bigtwo_logic_msg.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 456 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x53, 0xc1, 0x8e, 0xda, 0x30,
	0x10, 0x55, 0xc8, 0xb2, 0xcb, 0xce, 0x8a, 0x94, 0x75, 0x05, 0xeb, 0xd2, 0x0b, 0x42, 0x6a, 0xc5,
	0xa1, 0xe2, 0xd0, 0x2f, 0x68, 0xb5, 0xf7, 0xaa, 0x97, 0xaa, 0xbd, 0x59, 0xde, 0xc4, 0x80, 0xa5,
	0x60, 0xa7, 0xe3, 0x49, 0x11, 0x1f, 0xd8, 0xaf, 0xea, 0xa5, 0xf2, 0x04, 0x48, 0xa0, 0xf4, 0x98,
	0x37, 0xcf, 0xf3, 0xe6, 0xbd, 0x99, 0xc0, 0xe4, 0xc5, 0xae, 0x69, 0xe7, 0x55, 0xe9, 0xd7, 0x36,
	0x57, 0xdb, 0xb0, 0x5e, 0x56, 0xe8, 0xc9, 0x8b, 0xd4, 0x19, 0x9a, 0x8e, 0x5f, 0x74, 0x30, 0x11,
	0x54, 0x81, 0xb0, 0xce, 0xa9, 0xa9, 0x4d, 0x47, 0x06, 0xd1, 0xa3, 0xca, 0x7d, 0x61, 0x1a, 0x64,
	0xfe, 0x3b, 0x81, 0x37, 0x91, 0x76, 0x68, 0xb6, 0xd6, 0x5b, 0xa3, 0xac, 0x5b, 0x79, 0x85, 0x26,
	0x54, 0x62, 0x04, 0x83, 0xbc, 0x46, 0x55, 0x07, 0x83, 0x32, 0x99, 0x25, 0x8b, 0xa1, 0x10, 0x00,
	0x54, 0xa3, 0x53, 0x3b, 0xeb, 0x0c, 0xca, 0xde, 0x11, 0x5b, 0x59, 0x0c, 0xd4, 0xf0, 0x52, 0xc6,
	0x26, 0x90, 0x31, 0x2f, 0xd7, 0x58, 0xa8, 0x42, 0x93, 0x96, 0x37, 0xb3, 0x74, 0x31, 0x14, 0x4f,
	0xf0, 0x6a, 0xa3, 0x5d, 0xd1, 0xe0, 0xb9, 0xaf, 0x1d, 0xc9, 0x3e, 0x17, 0x26, 0x90, 0xb5, 0x05,
	0x7e, 0x70, 0xcb, 0xb8, 0x00, 0xe0, 0xa1, 0x02, 0x69, 0x32, 0xf2, 0x8e, 0x9b, 0x3f, 0xc2, 0xfd,
	0x4e, 0x5b, 0x52, 0x64, 0xb7, 0x46, 0x0e, 0x22, 0x34, 0x7f, 0x86, 0x71, 0xc7, 0x46, 0x20, 0x8d,
	0xd4, 0x58, 0x10, 0x00, 0xcd, 0x57, 0xc7, 0xc4, 0x7f, 0xb4, 0xe6, 0x1f, 0xe0, 0xa9, 0xd3, 0xc4,
	0xd7, 0xd4, 0x30, 0xd0, 0xfc, 0x8c, 0x92, 0x2d, 0x3b, 0x61, 0xf6, 0x06, 0xe4, 0x75, 0xf6, 0xd5,
	0xe0, 0xc6, 0x30, 0x3c, 0x51, 0x18, 0xee, 0x1d, 0xad, 0xb4, 0x7d, 0x53, 0x76, 0x3c, 0x82, 0x01,
	0x1a, 0xe2, 0x25, 0xc9, 0x1b, 0x36, 0x37, 0x3d, 0x53, 0xaa, 0x74, 0x08, 0xa7, 0xc1, 0xe6, 0x3f,
	0xce, 0xf6, 0xd7, 0xad, 0x85, 0x2a, 0x76, 0xe7, 0x2d, 0xf8, 0x5f, 0xa7, 0x39, 0xba, 0x93, 0xf5,
	0x8e, 0x69, 0xb4, 0xcf, 0xda, 0x15, 0x5e, 0xa8, 0xb6, 0x81, 0x45, 0xd5, 0x4f, 0x67, 0xaa, 0xdd,
	0xda, 0xc1, 0xfc, 0x46, 0x5b, 0x54, 0xb6, 0x38, 0x88, 0x9e, 0xb9, 0xec, 0x71, 0x7a, 0x7f, 0x12,
	0x78, 0x7b, 0x79, 0x78, 0x71, 0x4c, 0xe5, 0x3c, 0xd9, 0xd5, 0x9e, 0x77, 0x6c, 0x5d, 0xc8, 0x3d,
	0x9a, 0xc0, 0x81, 0xa7, 0xe2, 0x35, 0x3c, 0xec, 0xac, 0x7b, 0xd6, 0x58, 0x7c, 0xa9, 0xb7, 0x81,
	0xfb, 0xf4, 0xc5, 0x7b, 0xc8, 0x74, 0x59, 0x7e, 0xef, 0xe0, 0x31, 0xc5, 0x87, 0x8f, 0xd9, 0xd2,
	0x19, 0x5a, 0x46, 0x85, 0xa8, 0x1c, 0x22, 0xaf, 0x34, 0x2b, 0xba, 0x38, 0xc8, 0x7f, 0x79, 0xef,
	0x60, 0xa8, 0xcb, 0xb2, 0x43, 0xeb, 0x5f, 0xa5, 0x3d, 0xc2, 0xfd, 0x46, 0x87, 0xaf, 0x7a, 0xff,
	0xb9, 0x2c, 0xe5, 0xed, 0x2c, 0x59, 0xf4, 0xe3, 0xa5, 0x55, 0xfc, 0xfd, 0x2d, 0x66, 0x78, 0xc7,
	0xd8, 0x04, 0x32, 0xfe, 0x13, 0x5b, 0x2b, 0x83, 0x68, 0xe5, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xdf, 0x7a, 0xbb, 0x25, 0xbd, 0x03, 0x00, 0x00,
}
