// Code generated by protoc-gen-go. DO NOT EDIT.
// source: client_logic_msg.proto

package net

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// -----------------------------大厅服消息-------------------------------------------------------------------
// 心跳包
type MsgHeartTest struct {
	SvrTime          *uint32 `protobuf:"varint,1,opt,name=svr_time" json:"svr_time,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgHeartTest) Reset()                    { *m = MsgHeartTest{} }
func (m *MsgHeartTest) String() string            { return proto.CompactTextString(m) }
func (*MsgHeartTest) ProtoMessage()               {}
func (*MsgHeartTest) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{0} }

func (m *MsgHeartTest) GetSvrTime() uint32 {
	if m != nil && m.SvrTime != nil {
		return *m.SvrTime
	}
	return 0
}

// 登录
type MsgLoginReq struct {
	Uid              *uint32 `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	Key              []byte  `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
	Deviceid         []byte  `protobuf:"bytes,3,opt,name=deviceid" json:"deviceid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgLoginReq) Reset()                    { *m = MsgLoginReq{} }
func (m *MsgLoginReq) String() string            { return proto.CompactTextString(m) }
func (*MsgLoginReq) ProtoMessage()               {}
func (*MsgLoginReq) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{1} }

func (m *MsgLoginReq) GetUid() uint32 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *MsgLoginReq) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *MsgLoginReq) GetDeviceid() []byte {
	if m != nil {
		return m.Deviceid
	}
	return nil
}

// 登录返回
type MsgLoginRep struct {
	Result           *uint32 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	ServerTime       *uint32 `protobuf:"varint,2,opt,name=server_time" json:"server_time,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgLoginRep) Reset()                    { *m = MsgLoginRep{} }
func (m *MsgLoginRep) String() string            { return proto.CompactTextString(m) }
func (*MsgLoginRep) ProtoMessage()               {}
func (*MsgLoginRep) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{2} }

func (m *MsgLoginRep) GetResult() uint32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *MsgLoginRep) GetServerTime() uint32 {
	if m != nil && m.ServerTime != nil {
		return *m.ServerTime
	}
	return 0
}

// 通知离开游戏
type MsgNotifyLeaveRep struct {
	Result           *uint32 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgNotifyLeaveRep) Reset()                    { *m = MsgNotifyLeaveRep{} }
func (m *MsgNotifyLeaveRep) String() string            { return proto.CompactTextString(m) }
func (*MsgNotifyLeaveRep) ProtoMessage()               {}
func (*MsgNotifyLeaveRep) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{3} }

func (m *MsgNotifyLeaveRep) GetResult() uint32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

// 通知进入游戏
type MsgEnterGameRep struct {
	Result           *uint32 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgEnterGameRep) Reset()                    { *m = MsgEnterGameRep{} }
func (m *MsgEnterGameRep) String() string            { return proto.CompactTextString(m) }
func (*MsgEnterGameRep) ProtoMessage()               {}
func (*MsgEnterGameRep) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{4} }

func (m *MsgEnterGameRep) GetResult() uint32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

// 发送玩家信息
type MsgPlayerDataRep struct {
	BaseData         *BaseInfo `protobuf:"bytes,1,opt,name=base_data" json:"base_data,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *MsgPlayerDataRep) Reset()                    { *m = MsgPlayerDataRep{} }
func (m *MsgPlayerDataRep) String() string            { return proto.CompactTextString(m) }
func (*MsgPlayerDataRep) ProtoMessage()               {}
func (*MsgPlayerDataRep) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{5} }

func (m *MsgPlayerDataRep) GetBaseData() *BaseInfo {
	if m != nil {
		return m.BaseData
	}
	return nil
}

// 更新玩家数值
type MsgUpdateAccValue struct {
	Diamond          *int64 `protobuf:"varint,1,opt,name=diamond" json:"diamond,omitempty"`
	Coin             *int64 `protobuf:"varint,2,opt,name=coin" json:"coin,omitempty"`
	Score            *int64 `protobuf:"varint,3,opt,name=score" json:"score,omitempty"`
	Ingot            *int64 `protobuf:"varint,4,opt,name=ingot" json:"ingot,omitempty"`
	Cvalue           *int64 `protobuf:"varint,5,opt,name=cvalue" json:"cvalue,omitempty"`
	SafeCoin         *int64 `protobuf:"varint,6,opt,name=safe_coin" json:"safe_coin,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgUpdateAccValue) Reset()                    { *m = MsgUpdateAccValue{} }
func (m *MsgUpdateAccValue) String() string            { return proto.CompactTextString(m) }
func (*MsgUpdateAccValue) ProtoMessage()               {}
func (*MsgUpdateAccValue) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{6} }

func (m *MsgUpdateAccValue) GetDiamond() int64 {
	if m != nil && m.Diamond != nil {
		return *m.Diamond
	}
	return 0
}

func (m *MsgUpdateAccValue) GetCoin() int64 {
	if m != nil && m.Coin != nil {
		return *m.Coin
	}
	return 0
}

func (m *MsgUpdateAccValue) GetScore() int64 {
	if m != nil && m.Score != nil {
		return *m.Score
	}
	return 0
}

func (m *MsgUpdateAccValue) GetIngot() int64 {
	if m != nil && m.Ingot != nil {
		return *m.Ingot
	}
	return 0
}

func (m *MsgUpdateAccValue) GetCvalue() int64 {
	if m != nil && m.Cvalue != nil {
		return *m.Cvalue
	}
	return 0
}

func (m *MsgUpdateAccValue) GetSafeCoin() int64 {
	if m != nil && m.SafeCoin != nil {
		return *m.SafeCoin
	}
	return 0
}

// 更新基础数值
type MsgUpdateBaseValue struct {
	Safeboxstate     *uint32 `protobuf:"varint,1,opt,name=safeboxstate" json:"safeboxstate,omitempty"`
	Clogin           *uint32 `protobuf:"varint,2,opt,name=clogin" json:"clogin,omitempty"`
	Weeklogin        *uint32 `protobuf:"varint,3,opt,name=weeklogin" json:"weeklogin,omitempty"`
	Reward           *uint32 `protobuf:"varint,4,opt,name=reward" json:"reward,omitempty"`
	Bankrupt         *uint32 `protobuf:"varint,5,opt,name=bankrupt" json:"bankrupt,omitempty"`
	DayGameCount     *uint32 `protobuf:"varint,6,opt,name=day_game_count" json:"day_game_count,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgUpdateBaseValue) Reset()                    { *m = MsgUpdateBaseValue{} }
func (m *MsgUpdateBaseValue) String() string            { return proto.CompactTextString(m) }
func (*MsgUpdateBaseValue) ProtoMessage()               {}
func (*MsgUpdateBaseValue) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{7} }

func (m *MsgUpdateBaseValue) GetSafeboxstate() uint32 {
	if m != nil && m.Safeboxstate != nil {
		return *m.Safeboxstate
	}
	return 0
}

func (m *MsgUpdateBaseValue) GetClogin() uint32 {
	if m != nil && m.Clogin != nil {
		return *m.Clogin
	}
	return 0
}

func (m *MsgUpdateBaseValue) GetWeeklogin() uint32 {
	if m != nil && m.Weeklogin != nil {
		return *m.Weeklogin
	}
	return 0
}

func (m *MsgUpdateBaseValue) GetReward() uint32 {
	if m != nil && m.Reward != nil {
		return *m.Reward
	}
	return 0
}

func (m *MsgUpdateBaseValue) GetBankrupt() uint32 {
	if m != nil && m.Bankrupt != nil {
		return *m.Bankrupt
	}
	return 0
}

func (m *MsgUpdateBaseValue) GetDayGameCount() uint32 {
	if m != nil && m.DayGameCount != nil {
		return *m.DayGameCount
	}
	return 0
}

// 更新斗地主信息(待删除)
type MsgUpdateLandInfo struct {
	LandData         *LandInfo `protobuf:"bytes,1,opt,name=land_data" json:"land_data,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *MsgUpdateLandInfo) Reset()                    { *m = MsgUpdateLandInfo{} }
func (m *MsgUpdateLandInfo) String() string            { return proto.CompactTextString(m) }
func (*MsgUpdateLandInfo) ProtoMessage()               {}
func (*MsgUpdateLandInfo) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{8} }

func (m *MsgUpdateLandInfo) GetLandData() *LandInfo {
	if m != nil {
		return m.LandData
	}
	return nil
}

// 更新游戏数据
type MsgUpdateGameInfo struct {
	Data             *GameDataInfo `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *MsgUpdateGameInfo) Reset()                    { *m = MsgUpdateGameInfo{} }
func (m *MsgUpdateGameInfo) String() string            { return proto.CompactTextString(m) }
func (*MsgUpdateGameInfo) ProtoMessage()               {}
func (*MsgUpdateGameInfo) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{9} }

func (m *MsgUpdateGameInfo) GetData() *GameDataInfo {
	if m != nil {
		return m.Data
	}
	return nil
}

// 请求服务器信息
type MsgSvrsInfoReq struct {
	GameType         *uint32 `protobuf:"varint,1,opt,name=game_type" json:"game_type,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgSvrsInfoReq) Reset()                    { *m = MsgSvrsInfoReq{} }
func (m *MsgSvrsInfoReq) String() string            { return proto.CompactTextString(m) }
func (*MsgSvrsInfoReq) ProtoMessage()               {}
func (*MsgSvrsInfoReq) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{10} }

func (m *MsgSvrsInfoReq) GetGameType() uint32 {
	if m != nil && m.GameType != nil {
		return *m.GameType
	}
	return 0
}

// 发送游戏服务器信息
type MsgSvrsInfoRep struct {
	Svrs             []*SvrInfo `protobuf:"bytes,1,rep,name=svrs" json:"svrs,omitempty"`
	CurSvrid         *uint32    `protobuf:"varint,2,opt,name=cur_svrid" json:"cur_svrid,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *MsgSvrsInfoRep) Reset()                    { *m = MsgSvrsInfoRep{} }
func (m *MsgSvrsInfoRep) String() string            { return proto.CompactTextString(m) }
func (*MsgSvrsInfoRep) ProtoMessage()               {}
func (*MsgSvrsInfoRep) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{11} }

func (m *MsgSvrsInfoRep) GetSvrs() []*SvrInfo {
	if m != nil {
		return m.Svrs
	}
	return nil
}

func (m *MsgSvrsInfoRep) GetCurSvrid() uint32 {
	if m != nil && m.CurSvrid != nil {
		return *m.CurSvrid
	}
	return 0
}

// 进入游戏服务器
type MsgEnterGamesvrReq struct {
	Svrid            *uint32 `protobuf:"varint,1,opt,name=svrid" json:"svrid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgEnterGamesvrReq) Reset()                    { *m = MsgEnterGamesvrReq{} }
func (m *MsgEnterGamesvrReq) String() string            { return proto.CompactTextString(m) }
func (*MsgEnterGamesvrReq) ProtoMessage()               {}
func (*MsgEnterGamesvrReq) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{12} }

func (m *MsgEnterGamesvrReq) GetSvrid() uint32 {
	if m != nil && m.Svrid != nil {
		return *m.Svrid
	}
	return 0
}

// 进入游戏服务器返回
type MsgEnterGamesvrRep struct {
	Result           *uint32 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	Svrid            *uint32 `protobuf:"varint,2,opt,name=svrid" json:"svrid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgEnterGamesvrRep) Reset()                    { *m = MsgEnterGamesvrRep{} }
func (m *MsgEnterGamesvrRep) String() string            { return proto.CompactTextString(m) }
func (*MsgEnterGamesvrRep) ProtoMessage()               {}
func (*MsgEnterGamesvrRep) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{13} }

func (m *MsgEnterGamesvrRep) GetResult() uint32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *MsgEnterGamesvrRep) GetSvrid() uint32 {
	if m != nil && m.Svrid != nil {
		return *m.Svrid
	}
	return 0
}

// 登录保险箱
type MsgLoginSafeboxReq struct {
	Passwd           []byte `protobuf:"bytes,1,opt,name=passwd" json:"passwd,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgLoginSafeboxReq) Reset()                    { *m = MsgLoginSafeboxReq{} }
func (m *MsgLoginSafeboxReq) String() string            { return proto.CompactTextString(m) }
func (*MsgLoginSafeboxReq) ProtoMessage()               {}
func (*MsgLoginSafeboxReq) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{14} }

func (m *MsgLoginSafeboxReq) GetPasswd() []byte {
	if m != nil {
		return m.Passwd
	}
	return nil
}

type MsgLoginSafeboxRep struct {
	Result           *uint32 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgLoginSafeboxRep) Reset()                    { *m = MsgLoginSafeboxRep{} }
func (m *MsgLoginSafeboxRep) String() string            { return proto.CompactTextString(m) }
func (*MsgLoginSafeboxRep) ProtoMessage()               {}
func (*MsgLoginSafeboxRep) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{15} }

func (m *MsgLoginSafeboxRep) GetResult() uint32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

// 修改保险箱密码
type MsgChangeSafeboxPwdReq struct {
	OldPwd           []byte `protobuf:"bytes,1,opt,name=old_pwd" json:"old_pwd,omitempty"`
	NewPwd           []byte `protobuf:"bytes,2,opt,name=new_pwd" json:"new_pwd,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgChangeSafeboxPwdReq) Reset()                    { *m = MsgChangeSafeboxPwdReq{} }
func (m *MsgChangeSafeboxPwdReq) String() string            { return proto.CompactTextString(m) }
func (*MsgChangeSafeboxPwdReq) ProtoMessage()               {}
func (*MsgChangeSafeboxPwdReq) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{16} }

func (m *MsgChangeSafeboxPwdReq) GetOldPwd() []byte {
	if m != nil {
		return m.OldPwd
	}
	return nil
}

func (m *MsgChangeSafeboxPwdReq) GetNewPwd() []byte {
	if m != nil {
		return m.NewPwd
	}
	return nil
}

// 修改密码返回
type MsgChangeSafeboxPwdRep struct {
	Result           *uint32 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgChangeSafeboxPwdRep) Reset()                    { *m = MsgChangeSafeboxPwdRep{} }
func (m *MsgChangeSafeboxPwdRep) String() string            { return proto.CompactTextString(m) }
func (*MsgChangeSafeboxPwdRep) ProtoMessage()               {}
func (*MsgChangeSafeboxPwdRep) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{17} }

func (m *MsgChangeSafeboxPwdRep) GetResult() uint32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

// 保险箱存取操作
type MsgTakeSafeboxReq struct {
	TakeCoin         *int64 `protobuf:"varint,1,opt,name=take_coin" json:"take_coin,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgTakeSafeboxReq) Reset()                    { *m = MsgTakeSafeboxReq{} }
func (m *MsgTakeSafeboxReq) String() string            { return proto.CompactTextString(m) }
func (*MsgTakeSafeboxReq) ProtoMessage()               {}
func (*MsgTakeSafeboxReq) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{18} }

func (m *MsgTakeSafeboxReq) GetTakeCoin() int64 {
	if m != nil && m.TakeCoin != nil {
		return *m.TakeCoin
	}
	return 0
}

// 保险箱存取操作返回
type MsgTakeSafeboxRep struct {
	TakeCoin         *int64  `protobuf:"varint,1,opt,name=take_coin" json:"take_coin,omitempty"`
	Result           *uint32 `protobuf:"varint,2,opt,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgTakeSafeboxRep) Reset()                    { *m = MsgTakeSafeboxRep{} }
func (m *MsgTakeSafeboxRep) String() string            { return proto.CompactTextString(m) }
func (*MsgTakeSafeboxRep) ProtoMessage()               {}
func (*MsgTakeSafeboxRep) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{19} }

func (m *MsgTakeSafeboxRep) GetTakeCoin() int64 {
	if m != nil && m.TakeCoin != nil {
		return *m.TakeCoin
	}
	return 0
}

func (m *MsgTakeSafeboxRep) GetResult() uint32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

// 保险箱赠送操作
type MsgGiveSafeboxReq struct {
	GiveUid          *uint32 `protobuf:"varint,1,opt,name=give_uid" json:"give_uid,omitempty"`
	GiveCoin         *int64  `protobuf:"varint,2,opt,name=give_coin" json:"give_coin,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgGiveSafeboxReq) Reset()                    { *m = MsgGiveSafeboxReq{} }
func (m *MsgGiveSafeboxReq) String() string            { return proto.CompactTextString(m) }
func (*MsgGiveSafeboxReq) ProtoMessage()               {}
func (*MsgGiveSafeboxReq) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{20} }

func (m *MsgGiveSafeboxReq) GetGiveUid() uint32 {
	if m != nil && m.GiveUid != nil {
		return *m.GiveUid
	}
	return 0
}

func (m *MsgGiveSafeboxReq) GetGiveCoin() int64 {
	if m != nil && m.GiveCoin != nil {
		return *m.GiveCoin
	}
	return 0
}

// 保险箱赠送操作返回
type MsgGiveSafeboxRep struct {
	GiveUid          *uint32 `protobuf:"varint,1,opt,name=give_uid" json:"give_uid,omitempty"`
	GiveCoin         *int64  `protobuf:"varint,2,opt,name=give_coin" json:"give_coin,omitempty"`
	Result           *uint32 `protobuf:"varint,3,opt,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgGiveSafeboxRep) Reset()                    { *m = MsgGiveSafeboxRep{} }
func (m *MsgGiveSafeboxRep) String() string            { return proto.CompactTextString(m) }
func (*MsgGiveSafeboxRep) ProtoMessage()               {}
func (*MsgGiveSafeboxRep) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{21} }

func (m *MsgGiveSafeboxRep) GetGiveUid() uint32 {
	if m != nil && m.GiveUid != nil {
		return *m.GiveUid
	}
	return 0
}

func (m *MsgGiveSafeboxRep) GetGiveCoin() int64 {
	if m != nil && m.GiveCoin != nil {
		return *m.GiveCoin
	}
	return 0
}

func (m *MsgGiveSafeboxRep) GetResult() uint32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

// PHP转发广播消息
type MsgPhpBroadcastRep struct {
	Msg              []byte `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgPhpBroadcastRep) Reset()                    { *m = MsgPhpBroadcastRep{} }
func (m *MsgPhpBroadcastRep) String() string            { return proto.CompactTextString(m) }
func (*MsgPhpBroadcastRep) ProtoMessage()               {}
func (*MsgPhpBroadcastRep) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{22} }

func (m *MsgPhpBroadcastRep) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

// 系统广播
type MsgSystemBroadcastRep struct {
	Msg              []byte `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgSystemBroadcastRep) Reset()                    { *m = MsgSystemBroadcastRep{} }
func (m *MsgSystemBroadcastRep) String() string            { return proto.CompactTextString(m) }
func (*MsgSystemBroadcastRep) ProtoMessage()               {}
func (*MsgSystemBroadcastRep) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{23} }

func (m *MsgSystemBroadcastRep) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

// -----------------任务
// 获得所有任务数据
type MsgSendAllMissionRep struct {
	Missions         []*MissionData `protobuf:"bytes,1,rep,name=missions" json:"missions,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *MsgSendAllMissionRep) Reset()                    { *m = MsgSendAllMissionRep{} }
func (m *MsgSendAllMissionRep) String() string            { return proto.CompactTextString(m) }
func (*MsgSendAllMissionRep) ProtoMessage()               {}
func (*MsgSendAllMissionRep) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{24} }

func (m *MsgSendAllMissionRep) GetMissions() []*MissionData {
	if m != nil {
		return m.Missions
	}
	return nil
}

// 发送单条任务数据
type MsgSendMissionRep struct {
	Mission          *MissionData `protobuf:"bytes,1,opt,name=mission" json:"mission,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *MsgSendMissionRep) Reset()                    { *m = MsgSendMissionRep{} }
func (m *MsgSendMissionRep) String() string            { return proto.CompactTextString(m) }
func (*MsgSendMissionRep) ProtoMessage()               {}
func (*MsgSendMissionRep) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{25} }

func (m *MsgSendMissionRep) GetMission() *MissionData {
	if m != nil {
		return m.Mission
	}
	return nil
}

// 获得用户奖励
type MsgGetMissionPrizeReq struct {
	Msid             *uint32 `protobuf:"varint,1,opt,name=msid" json:"msid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgGetMissionPrizeReq) Reset()                    { *m = MsgGetMissionPrizeReq{} }
func (m *MsgGetMissionPrizeReq) String() string            { return proto.CompactTextString(m) }
func (*MsgGetMissionPrizeReq) ProtoMessage()               {}
func (*MsgGetMissionPrizeReq) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{26} }

func (m *MsgGetMissionPrizeReq) GetMsid() uint32 {
	if m != nil && m.Msid != nil {
		return *m.Msid
	}
	return 0
}

type MsgGetMissionPrizeRep struct {
	Result           *uint32      `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	Mission          *MissionData `protobuf:"bytes,2,opt,name=mission" json:"mission,omitempty"`
	Baseinfo         *BaseInfo    `protobuf:"bytes,3,opt,name=baseinfo" json:"baseinfo,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *MsgGetMissionPrizeRep) Reset()                    { *m = MsgGetMissionPrizeRep{} }
func (m *MsgGetMissionPrizeRep) String() string            { return proto.CompactTextString(m) }
func (*MsgGetMissionPrizeRep) ProtoMessage()               {}
func (*MsgGetMissionPrizeRep) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{27} }

func (m *MsgGetMissionPrizeRep) GetResult() uint32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *MsgGetMissionPrizeRep) GetMission() *MissionData {
	if m != nil {
		return m.Mission
	}
	return nil
}

func (m *MsgGetMissionPrizeRep) GetBaseinfo() *BaseInfo {
	if m != nil {
		return m.Baseinfo
	}
	return nil
}

// 连续登陆奖励
type MsgGetLoginRewardReq struct {
	RewardFlag       *uint32 `protobuf:"varint,1,opt,name=reward_flag" json:"reward_flag,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgGetLoginRewardReq) Reset()                    { *m = MsgGetLoginRewardReq{} }
func (m *MsgGetLoginRewardReq) String() string            { return proto.CompactTextString(m) }
func (*MsgGetLoginRewardReq) ProtoMessage()               {}
func (*MsgGetLoginRewardReq) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{28} }

func (m *MsgGetLoginRewardReq) GetRewardFlag() uint32 {
	if m != nil && m.RewardFlag != nil {
		return *m.RewardFlag
	}
	return 0
}

type MsgGetLoginRewardRep struct {
	RewardFlag       *uint32 `protobuf:"varint,1,opt,name=reward_flag" json:"reward_flag,omitempty"`
	Result           *uint32 `protobuf:"varint,2,opt,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgGetLoginRewardRep) Reset()                    { *m = MsgGetLoginRewardRep{} }
func (m *MsgGetLoginRewardRep) String() string            { return proto.CompactTextString(m) }
func (*MsgGetLoginRewardRep) ProtoMessage()               {}
func (*MsgGetLoginRewardRep) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{29} }

func (m *MsgGetLoginRewardRep) GetRewardFlag() uint32 {
	if m != nil && m.RewardFlag != nil {
		return *m.RewardFlag
	}
	return 0
}

func (m *MsgGetLoginRewardRep) GetResult() uint32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

// 破产补助
type MsgGetBankruptHelpReq struct {
	HelpCount        *uint32 `protobuf:"varint,1,opt,name=help_count" json:"help_count,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgGetBankruptHelpReq) Reset()                    { *m = MsgGetBankruptHelpReq{} }
func (m *MsgGetBankruptHelpReq) String() string            { return proto.CompactTextString(m) }
func (*MsgGetBankruptHelpReq) ProtoMessage()               {}
func (*MsgGetBankruptHelpReq) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{30} }

func (m *MsgGetBankruptHelpReq) GetHelpCount() uint32 {
	if m != nil && m.HelpCount != nil {
		return *m.HelpCount
	}
	return 0
}

type MsgGetBankruptHelpRep struct {
	Result           *uint32 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	BankruptCount    *uint32 `protobuf:"varint,2,opt,name=bankrupt_count" json:"bankrupt_count,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgGetBankruptHelpRep) Reset()                    { *m = MsgGetBankruptHelpRep{} }
func (m *MsgGetBankruptHelpRep) String() string            { return proto.CompactTextString(m) }
func (*MsgGetBankruptHelpRep) ProtoMessage()               {}
func (*MsgGetBankruptHelpRep) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{31} }

func (m *MsgGetBankruptHelpRep) GetResult() uint32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *MsgGetBankruptHelpRep) GetBankruptCount() uint32 {
	if m != nil && m.BankruptCount != nil {
		return *m.BankruptCount
	}
	return 0
}

// 兑换财富币积分
type MsgExchangeScoreReq struct {
	ExchangeType     *uint32 `protobuf:"varint,1,opt,name=exchange_type" json:"exchange_type,omitempty"`
	ExchangeId       *uint32 `protobuf:"varint,2,opt,name=exchange_id" json:"exchange_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgExchangeScoreReq) Reset()                    { *m = MsgExchangeScoreReq{} }
func (m *MsgExchangeScoreReq) String() string            { return proto.CompactTextString(m) }
func (*MsgExchangeScoreReq) ProtoMessage()               {}
func (*MsgExchangeScoreReq) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{32} }

func (m *MsgExchangeScoreReq) GetExchangeType() uint32 {
	if m != nil && m.ExchangeType != nil {
		return *m.ExchangeType
	}
	return 0
}

func (m *MsgExchangeScoreReq) GetExchangeId() uint32 {
	if m != nil && m.ExchangeId != nil {
		return *m.ExchangeId
	}
	return 0
}

type MsgExchangeScoreRep struct {
	ExchangeType     *uint32 `protobuf:"varint,1,opt,name=exchange_type" json:"exchange_type,omitempty"`
	ExchangeId       *uint32 `protobuf:"varint,2,opt,name=exchange_id" json:"exchange_id,omitempty"`
	Result           *uint32 `protobuf:"varint,3,opt,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgExchangeScoreRep) Reset()                    { *m = MsgExchangeScoreRep{} }
func (m *MsgExchangeScoreRep) String() string            { return proto.CompactTextString(m) }
func (*MsgExchangeScoreRep) ProtoMessage()               {}
func (*MsgExchangeScoreRep) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{33} }

func (m *MsgExchangeScoreRep) GetExchangeType() uint32 {
	if m != nil && m.ExchangeType != nil {
		return *m.ExchangeType
	}
	return 0
}

func (m *MsgExchangeScoreRep) GetExchangeId() uint32 {
	if m != nil && m.ExchangeId != nil {
		return *m.ExchangeId
	}
	return 0
}

func (m *MsgExchangeScoreRep) GetResult() uint32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

// 喇叭
type MsgSpeakBroadcastReq struct {
	Msg              []byte `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgSpeakBroadcastReq) Reset()                    { *m = MsgSpeakBroadcastReq{} }
func (m *MsgSpeakBroadcastReq) String() string            { return proto.CompactTextString(m) }
func (*MsgSpeakBroadcastReq) ProtoMessage()               {}
func (*MsgSpeakBroadcastReq) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{34} }

func (m *MsgSpeakBroadcastReq) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

type MsgSpeakBroadcastRep struct {
	SendId           *uint32 `protobuf:"varint,1,opt,name=send_id" json:"send_id,omitempty"`
	SendName         []byte  `protobuf:"bytes,2,opt,name=send_name" json:"send_name,omitempty"`
	Msg              []byte  `protobuf:"bytes,3,opt,name=msg" json:"msg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgSpeakBroadcastRep) Reset()                    { *m = MsgSpeakBroadcastRep{} }
func (m *MsgSpeakBroadcastRep) String() string            { return proto.CompactTextString(m) }
func (*MsgSpeakBroadcastRep) ProtoMessage()               {}
func (*MsgSpeakBroadcastRep) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{35} }

func (m *MsgSpeakBroadcastRep) GetSendId() uint32 {
	if m != nil && m.SendId != nil {
		return *m.SendId
	}
	return 0
}

func (m *MsgSpeakBroadcastRep) GetSendName() []byte {
	if m != nil {
		return m.SendName
	}
	return nil
}

func (m *MsgSpeakBroadcastRep) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

type MsgGetHistorySpeak struct {
	GetTime          *uint32 `protobuf:"varint,1,opt,name=get_time" json:"get_time,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgGetHistorySpeak) Reset()                    { *m = MsgGetHistorySpeak{} }
func (m *MsgGetHistorySpeak) String() string            { return proto.CompactTextString(m) }
func (*MsgGetHistorySpeak) ProtoMessage()               {}
func (*MsgGetHistorySpeak) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{36} }

func (m *MsgGetHistorySpeak) GetGetTime() uint32 {
	if m != nil && m.GetTime != nil {
		return *m.GetTime
	}
	return 0
}

type MsgSendHistorySpeak struct {
	Msgs             []*MsgSpeakBroadcastRep `protobuf:"bytes,1,rep,name=msgs" json:"msgs,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *MsgSendHistorySpeak) Reset()                    { *m = MsgSendHistorySpeak{} }
func (m *MsgSendHistorySpeak) String() string            { return proto.CompactTextString(m) }
func (*MsgSendHistorySpeak) ProtoMessage()               {}
func (*MsgSendHistorySpeak) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{37} }

func (m *MsgSendHistorySpeak) GetMsgs() []*MsgSpeakBroadcastRep {
	if m != nil {
		return m.Msgs
	}
	return nil
}

type MsgSpeakOperRep struct {
	Result           *uint32 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	Cdtime           *uint32 `protobuf:"varint,2,opt,name=cdtime" json:"cdtime,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgSpeakOperRep) Reset()                    { *m = MsgSpeakOperRep{} }
func (m *MsgSpeakOperRep) String() string            { return proto.CompactTextString(m) }
func (*MsgSpeakOperRep) ProtoMessage()               {}
func (*MsgSpeakOperRep) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{38} }

func (m *MsgSpeakOperRep) GetResult() uint32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *MsgSpeakOperRep) GetCdtime() uint32 {
	if m != nil && m.Cdtime != nil {
		return *m.Cdtime
	}
	return 0
}

type MsgGetServerInfo struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgGetServerInfo) Reset()                    { *m = MsgGetServerInfo{} }
func (m *MsgGetServerInfo) String() string            { return proto.CompactTextString(m) }
func (*MsgGetServerInfo) ProtoMessage()               {}
func (*MsgGetServerInfo) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{39} }

type ServerInfo struct {
	Svrid            *uint32 `protobuf:"varint,1,opt,name=svrid" json:"svrid,omitempty"`
	PlayerNum        *uint32 `protobuf:"varint,2,opt,name=player_num" json:"player_num,omitempty"`
	RobotNum         *uint32 `protobuf:"varint,3,opt,name=robot_num" json:"robot_num,omitempty"`
	GameType         *uint32 `protobuf:"varint,4,opt,name=game_type" json:"game_type,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ServerInfo) Reset()                    { *m = ServerInfo{} }
func (m *ServerInfo) String() string            { return proto.CompactTextString(m) }
func (*ServerInfo) ProtoMessage()               {}
func (*ServerInfo) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{40} }

func (m *ServerInfo) GetSvrid() uint32 {
	if m != nil && m.Svrid != nil {
		return *m.Svrid
	}
	return 0
}

func (m *ServerInfo) GetPlayerNum() uint32 {
	if m != nil && m.PlayerNum != nil {
		return *m.PlayerNum
	}
	return 0
}

func (m *ServerInfo) GetRobotNum() uint32 {
	if m != nil && m.RobotNum != nil {
		return *m.RobotNum
	}
	return 0
}

func (m *ServerInfo) GetGameType() uint32 {
	if m != nil && m.GameType != nil {
		return *m.GameType
	}
	return 0
}

type MsgSendServerInfo struct {
	Servers          []*ServerInfo `protobuf:"bytes,1,rep,name=servers" json:"servers,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *MsgSendServerInfo) Reset()                    { *m = MsgSendServerInfo{} }
func (m *MsgSendServerInfo) String() string            { return proto.CompactTextString(m) }
func (*MsgSendServerInfo) ProtoMessage()               {}
func (*MsgSendServerInfo) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{41} }

func (m *MsgSendServerInfo) GetServers() []*ServerInfo {
	if m != nil {
		return m.Servers
	}
	return nil
}

// 玩家请求私人房游戏信息
type MsgPrivateGameInfoReq struct {
	GameType         *uint32 `protobuf:"varint,1,opt,name=game_type" json:"game_type,omitempty"`
	GameNum          *uint32 `protobuf:"varint,2,opt,name=game_num" json:"game_num,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgPrivateGameInfoReq) Reset()                    { *m = MsgPrivateGameInfoReq{} }
func (m *MsgPrivateGameInfoReq) String() string            { return proto.CompactTextString(m) }
func (*MsgPrivateGameInfoReq) ProtoMessage()               {}
func (*MsgPrivateGameInfoReq) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{42} }

func (m *MsgPrivateGameInfoReq) GetGameType() uint32 {
	if m != nil && m.GameType != nil {
		return *m.GameType
	}
	return 0
}

func (m *MsgPrivateGameInfoReq) GetGameNum() uint32 {
	if m != nil && m.GameNum != nil {
		return *m.GameNum
	}
	return 0
}

type MsgPrivateGameInfoRep struct {
	Result           *uint32            `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	GameLog          []*PrivateGameInfo `protobuf:"bytes,2,rep,name=game_log" json:"game_log,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *MsgPrivateGameInfoRep) Reset()                    { *m = MsgPrivateGameInfoRep{} }
func (m *MsgPrivateGameInfoRep) String() string            { return proto.CompactTextString(m) }
func (*MsgPrivateGameInfoRep) ProtoMessage()               {}
func (*MsgPrivateGameInfoRep) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{43} }

func (m *MsgPrivateGameInfoRep) GetResult() uint32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *MsgPrivateGameInfoRep) GetGameLog() []*PrivateGameInfo {
	if m != nil {
		return m.GameLog
	}
	return nil
}

// 私人房游戏结算
type MsgPrivateGameResult struct {
	GameInfo         *PrivateGameInfo `protobuf:"bytes,1,opt,name=game_info" json:"game_info,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *MsgPrivateGameResult) Reset()                    { *m = MsgPrivateGameResult{} }
func (m *MsgPrivateGameResult) String() string            { return proto.CompactTextString(m) }
func (*MsgPrivateGameResult) ProtoMessage()               {}
func (*MsgPrivateGameResult) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{44} }

func (m *MsgPrivateGameResult) GetGameInfo() *PrivateGameInfo {
	if m != nil {
		return m.GameInfo
	}
	return nil
}

// 请求自己创建的桌子信息
type MsgSelfPrivateListReq struct {
	GameType         *uint32 `protobuf:"varint,1,opt,name=game_type" json:"game_type,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgSelfPrivateListReq) Reset()                    { *m = MsgSelfPrivateListReq{} }
func (m *MsgSelfPrivateListReq) String() string            { return proto.CompactTextString(m) }
func (*MsgSelfPrivateListReq) ProtoMessage()               {}
func (*MsgSelfPrivateListReq) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{45} }

func (m *MsgSelfPrivateListReq) GetGameType() uint32 {
	if m != nil && m.GameType != nil {
		return *m.GameType
	}
	return 0
}

type MsgSelfPrivateListRep struct {
	PrivateInfo      []*PrivateTableInfo `protobuf:"bytes,1,rep,name=private_info" json:"private_info,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *MsgSelfPrivateListRep) Reset()                    { *m = MsgSelfPrivateListRep{} }
func (m *MsgSelfPrivateListRep) String() string            { return proto.CompactTextString(m) }
func (*MsgSelfPrivateListRep) ProtoMessage()               {}
func (*MsgSelfPrivateListRep) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{46} }

func (m *MsgSelfPrivateListRep) GetPrivateInfo() []*PrivateTableInfo {
	if m != nil {
		return m.PrivateInfo
	}
	return nil
}

// ---------------游戏服消息--------------------------------------------------------------------------
// 请求房间列表信息
type MsgRoomsInfoReq struct {
	GameType         *uint32 `protobuf:"varint,1,opt,name=game_type" json:"game_type,omitempty"`
	SvrId            *uint32 `protobuf:"varint,2,opt,name=svr_id" json:"svr_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgRoomsInfoReq) Reset()                    { *m = MsgRoomsInfoReq{} }
func (m *MsgRoomsInfoReq) String() string            { return proto.CompactTextString(m) }
func (*MsgRoomsInfoReq) ProtoMessage()               {}
func (*MsgRoomsInfoReq) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{47} }

func (m *MsgRoomsInfoReq) GetGameType() uint32 {
	if m != nil && m.GameType != nil {
		return *m.GameType
	}
	return 0
}

func (m *MsgRoomsInfoReq) GetSvrId() uint32 {
	if m != nil && m.SvrId != nil {
		return *m.SvrId
	}
	return 0
}

// 发送游戏房间列表
type MsgRoomsInfoRep struct {
	Rooms            []*RoomInfo `protobuf:"bytes,1,rep,name=rooms" json:"rooms,omitempty"`
	CurRoomid        *uint32     `protobuf:"varint,2,opt,name=cur_roomid" json:"cur_roomid,omitempty"`
	SvrId            *uint32     `protobuf:"varint,3,opt,name=svr_id" json:"svr_id,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *MsgRoomsInfoRep) Reset()                    { *m = MsgRoomsInfoRep{} }
func (m *MsgRoomsInfoRep) String() string            { return proto.CompactTextString(m) }
func (*MsgRoomsInfoRep) ProtoMessage()               {}
func (*MsgRoomsInfoRep) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{48} }

func (m *MsgRoomsInfoRep) GetRooms() []*RoomInfo {
	if m != nil {
		return m.Rooms
	}
	return nil
}

func (m *MsgRoomsInfoRep) GetCurRoomid() uint32 {
	if m != nil && m.CurRoomid != nil {
		return *m.CurRoomid
	}
	return 0
}

func (m *MsgRoomsInfoRep) GetSvrId() uint32 {
	if m != nil && m.SvrId != nil {
		return *m.SvrId
	}
	return 0
}

// 返回大厅
type MsgBackLobbyReq struct {
	Uid              *uint32 `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgBackLobbyReq) Reset()                    { *m = MsgBackLobbyReq{} }
func (m *MsgBackLobbyReq) String() string            { return proto.CompactTextString(m) }
func (*MsgBackLobbyReq) ProtoMessage()               {}
func (*MsgBackLobbyReq) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{49} }

func (m *MsgBackLobbyReq) GetUid() uint32 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

// 返回大厅反馈
type MsgBackLobbyRep struct {
	Result           *uint32 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgBackLobbyRep) Reset()                    { *m = MsgBackLobbyRep{} }
func (m *MsgBackLobbyRep) String() string            { return proto.CompactTextString(m) }
func (*MsgBackLobbyRep) ProtoMessage()               {}
func (*MsgBackLobbyRep) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{50} }

func (m *MsgBackLobbyRep) GetResult() uint32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

// 跳转游戏服务器
type MsgGotoGamesvrReq struct {
	Svrid            *uint32 `protobuf:"varint,1,opt,name=svrid" json:"svrid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgGotoGamesvrReq) Reset()                    { *m = MsgGotoGamesvrReq{} }
func (m *MsgGotoGamesvrReq) String() string            { return proto.CompactTextString(m) }
func (*MsgGotoGamesvrReq) ProtoMessage()               {}
func (*MsgGotoGamesvrReq) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{51} }

func (m *MsgGotoGamesvrReq) GetSvrid() uint32 {
	if m != nil && m.Svrid != nil {
		return *m.Svrid
	}
	return 0
}

type MsgGotoGamesvrRep struct {
	Result           *uint32 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	Svrid            *uint32 `protobuf:"varint,2,opt,name=svrid" json:"svrid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgGotoGamesvrRep) Reset()                    { *m = MsgGotoGamesvrRep{} }
func (m *MsgGotoGamesvrRep) String() string            { return proto.CompactTextString(m) }
func (*MsgGotoGamesvrRep) ProtoMessage()               {}
func (*MsgGotoGamesvrRep) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{52} }

func (m *MsgGotoGamesvrRep) GetResult() uint32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *MsgGotoGamesvrRep) GetSvrid() uint32 {
	if m != nil && m.Svrid != nil {
		return *m.Svrid
	}
	return 0
}

// 进入房间
type MsgEnterRoomReq struct {
	RoomId           *uint32 `protobuf:"varint,1,opt,name=room_id" json:"room_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgEnterRoomReq) Reset()                    { *m = MsgEnterRoomReq{} }
func (m *MsgEnterRoomReq) String() string            { return proto.CompactTextString(m) }
func (*MsgEnterRoomReq) ProtoMessage()               {}
func (*MsgEnterRoomReq) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{53} }

func (m *MsgEnterRoomReq) GetRoomId() uint32 {
	if m != nil && m.RoomId != nil {
		return *m.RoomId
	}
	return 0
}

// 进入房间返回
type MsgEnterRoomRep struct {
	Result           *uint32   `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	Room             *RoomInfo `protobuf:"bytes,2,opt,name=room" json:"room,omitempty"`
	CurTable         *uint32   `protobuf:"varint,3,opt,name=cur_table" json:"cur_table,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *MsgEnterRoomRep) Reset()                    { *m = MsgEnterRoomRep{} }
func (m *MsgEnterRoomRep) String() string            { return proto.CompactTextString(m) }
func (*MsgEnterRoomRep) ProtoMessage()               {}
func (*MsgEnterRoomRep) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{54} }

func (m *MsgEnterRoomRep) GetResult() uint32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *MsgEnterRoomRep) GetRoom() *RoomInfo {
	if m != nil {
		return m.Room
	}
	return nil
}

func (m *MsgEnterRoomRep) GetCurTable() uint32 {
	if m != nil && m.CurTable != nil {
		return *m.CurTable
	}
	return 0
}

// 通知离开房间
type MsgNotifyLeaveRoomRep struct {
	LeaveType        *uint32 `protobuf:"varint,1,opt,name=leave_type" json:"leave_type,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgNotifyLeaveRoomRep) Reset()                    { *m = MsgNotifyLeaveRoomRep{} }
func (m *MsgNotifyLeaveRoomRep) String() string            { return proto.CompactTextString(m) }
func (*MsgNotifyLeaveRoomRep) ProtoMessage()               {}
func (*MsgNotifyLeaveRoomRep) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{55} }

func (m *MsgNotifyLeaveRoomRep) GetLeaveType() uint32 {
	if m != nil && m.LeaveType != nil {
		return *m.LeaveType
	}
	return 0
}

// 请求桌子列表
type MsgTableListReq struct {
	TableId          *uint32 `protobuf:"varint,1,opt,name=table_id" json:"table_id,omitempty"`
	SeachType        *uint32 `protobuf:"varint,2,opt,name=seach_type" json:"seach_type,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgTableListReq) Reset()                    { *m = MsgTableListReq{} }
func (m *MsgTableListReq) String() string            { return proto.CompactTextString(m) }
func (*MsgTableListReq) ProtoMessage()               {}
func (*MsgTableListReq) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{56} }

func (m *MsgTableListReq) GetTableId() uint32 {
	if m != nil && m.TableId != nil {
		return *m.TableId
	}
	return 0
}

func (m *MsgTableListReq) GetSeachType() uint32 {
	if m != nil && m.SeachType != nil {
		return *m.SeachType
	}
	return 0
}

// 桌子列表
type MsgTableListRep struct {
	Tables           []*TableFaceInfo `protobuf:"bytes,1,rep,name=tables" json:"tables,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *MsgTableListRep) Reset()                    { *m = MsgTableListRep{} }
func (m *MsgTableListRep) String() string            { return proto.CompactTextString(m) }
func (*MsgTableListRep) ProtoMessage()               {}
func (*MsgTableListRep) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{57} }

func (m *MsgTableListRep) GetTables() []*TableFaceInfo {
	if m != nil {
		return m.Tables
	}
	return nil
}

// 创建桌子
type MsgCreateTableReq struct {
	Deal             *uint32           `protobuf:"varint,1,opt,name=deal" json:"deal,omitempty"`
	BaseScore        *int64            `protobuf:"varint,2,opt,name=base_score" json:"base_score,omitempty"`
	OpenRound        *uint32           `protobuf:"varint,3,opt,name=open_round" json:"open_round,omitempty"`
	SeatNum          *uint32           `protobuf:"varint,4,opt,name=seat_num" json:"seat_num,omitempty"`
	ServerId         *uint32           `protobuf:"varint,5,opt,name=server_id" json:"server_id,omitempty"`
	IsAa             *uint32           `protobuf:"varint,6,opt,name=is_aa" json:"is_aa,omitempty"`
	Params           []*PrivateKvParam `protobuf:"bytes,7,rep,name=params" json:"params,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *MsgCreateTableReq) Reset()                    { *m = MsgCreateTableReq{} }
func (m *MsgCreateTableReq) String() string            { return proto.CompactTextString(m) }
func (*MsgCreateTableReq) ProtoMessage()               {}
func (*MsgCreateTableReq) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{58} }

func (m *MsgCreateTableReq) GetDeal() uint32 {
	if m != nil && m.Deal != nil {
		return *m.Deal
	}
	return 0
}

func (m *MsgCreateTableReq) GetBaseScore() int64 {
	if m != nil && m.BaseScore != nil {
		return *m.BaseScore
	}
	return 0
}

func (m *MsgCreateTableReq) GetOpenRound() uint32 {
	if m != nil && m.OpenRound != nil {
		return *m.OpenRound
	}
	return 0
}

func (m *MsgCreateTableReq) GetSeatNum() uint32 {
	if m != nil && m.SeatNum != nil {
		return *m.SeatNum
	}
	return 0
}

func (m *MsgCreateTableReq) GetServerId() uint32 {
	if m != nil && m.ServerId != nil {
		return *m.ServerId
	}
	return 0
}

func (m *MsgCreateTableReq) GetIsAa() uint32 {
	if m != nil && m.IsAa != nil {
		return *m.IsAa
	}
	return 0
}

func (m *MsgCreateTableReq) GetParams() []*PrivateKvParam {
	if m != nil {
		return m.Params
	}
	return nil
}

// 创建桌子返回
type MsgCreateTableRep struct {
	Result           *uint32 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	TableId          *uint32 `protobuf:"varint,2,opt,name=table_id" json:"table_id,omitempty"`
	Passwd           []byte  `protobuf:"bytes,3,opt,name=passwd" json:"passwd,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgCreateTableRep) Reset()                    { *m = MsgCreateTableRep{} }
func (m *MsgCreateTableRep) String() string            { return proto.CompactTextString(m) }
func (*MsgCreateTableRep) ProtoMessage()               {}
func (*MsgCreateTableRep) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{59} }

func (m *MsgCreateTableRep) GetResult() uint32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *MsgCreateTableRep) GetTableId() uint32 {
	if m != nil && m.TableId != nil {
		return *m.TableId
	}
	return 0
}

func (m *MsgCreateTableRep) GetPasswd() []byte {
	if m != nil {
		return m.Passwd
	}
	return nil
}

// 续费桌子
type MsgRenewTableReq struct {
	TableId          *uint32 `protobuf:"varint,1,opt,name=table_id" json:"table_id,omitempty"`
	RenewDays        *uint32 `protobuf:"varint,2,opt,name=renew_days" json:"renew_days,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgRenewTableReq) Reset()                    { *m = MsgRenewTableReq{} }
func (m *MsgRenewTableReq) String() string            { return proto.CompactTextString(m) }
func (*MsgRenewTableReq) ProtoMessage()               {}
func (*MsgRenewTableReq) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{60} }

func (m *MsgRenewTableReq) GetTableId() uint32 {
	if m != nil && m.TableId != nil {
		return *m.TableId
	}
	return 0
}

func (m *MsgRenewTableReq) GetRenewDays() uint32 {
	if m != nil && m.RenewDays != nil {
		return *m.RenewDays
	}
	return 0
}

type MsgRenewTableRep struct {
	TableId          *uint32 `protobuf:"varint,1,opt,name=table_id" json:"table_id,omitempty"`
	RenewDays        *uint32 `protobuf:"varint,2,opt,name=renew_days" json:"renew_days,omitempty"`
	Result           *uint32 `protobuf:"varint,3,opt,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgRenewTableRep) Reset()                    { *m = MsgRenewTableRep{} }
func (m *MsgRenewTableRep) String() string            { return proto.CompactTextString(m) }
func (*MsgRenewTableRep) ProtoMessage()               {}
func (*MsgRenewTableRep) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{61} }

func (m *MsgRenewTableRep) GetTableId() uint32 {
	if m != nil && m.TableId != nil {
		return *m.TableId
	}
	return 0
}

func (m *MsgRenewTableRep) GetRenewDays() uint32 {
	if m != nil && m.RenewDays != nil {
		return *m.RenewDays
	}
	return 0
}

func (m *MsgRenewTableRep) GetResult() uint32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

// 离开桌子
type MsgLeaveTableReq struct {
	TableId          *uint32 `protobuf:"varint,1,opt,name=table_id" json:"table_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgLeaveTableReq) Reset()                    { *m = MsgLeaveTableReq{} }
func (m *MsgLeaveTableReq) String() string            { return proto.CompactTextString(m) }
func (*MsgLeaveTableReq) ProtoMessage()               {}
func (*MsgLeaveTableReq) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{62} }

func (m *MsgLeaveTableReq) GetTableId() uint32 {
	if m != nil && m.TableId != nil {
		return *m.TableId
	}
	return 0
}

// 离开桌子返回
type MsgLeaveTableRep struct {
	Result           *uint32 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgLeaveTableRep) Reset()                    { *m = MsgLeaveTableRep{} }
func (m *MsgLeaveTableRep) String() string            { return proto.CompactTextString(m) }
func (*MsgLeaveTableRep) ProtoMessage()               {}
func (*MsgLeaveTableRep) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{63} }

func (m *MsgLeaveTableRep) GetResult() uint32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

// 进入桌子
type MsgEnterTableReq struct {
	TableId          *uint32 `protobuf:"varint,1,opt,name=table_id" json:"table_id,omitempty"`
	Passwd           []byte  `protobuf:"bytes,2,opt,name=passwd" json:"passwd,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgEnterTableReq) Reset()                    { *m = MsgEnterTableReq{} }
func (m *MsgEnterTableReq) String() string            { return proto.CompactTextString(m) }
func (*MsgEnterTableReq) ProtoMessage()               {}
func (*MsgEnterTableReq) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{64} }

func (m *MsgEnterTableReq) GetTableId() uint32 {
	if m != nil && m.TableId != nil {
		return *m.TableId
	}
	return 0
}

func (m *MsgEnterTableReq) GetPasswd() []byte {
	if m != nil {
		return m.Passwd
	}
	return nil
}

type MsgEnterTableRep struct {
	TableId          *uint32 `protobuf:"varint,1,opt,name=table_id" json:"table_id,omitempty"`
	Result           *uint32 `protobuf:"varint,2,opt,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgEnterTableRep) Reset()                    { *m = MsgEnterTableRep{} }
func (m *MsgEnterTableRep) String() string            { return proto.CompactTextString(m) }
func (*MsgEnterTableRep) ProtoMessage()               {}
func (*MsgEnterTableRep) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{65} }

func (m *MsgEnterTableRep) GetTableId() uint32 {
	if m != nil && m.TableId != nil {
		return *m.TableId
	}
	return 0
}

func (m *MsgEnterTableRep) GetResult() uint32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

// 桌子信息
type MsgTableInfoRep struct {
	TableInfo        *TableFaceInfo `protobuf:"bytes,1,opt,name=table_info" json:"table_info,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *MsgTableInfoRep) Reset()                    { *m = MsgTableInfoRep{} }
func (m *MsgTableInfoRep) String() string            { return proto.CompactTextString(m) }
func (*MsgTableInfoRep) ProtoMessage()               {}
func (*MsgTableInfoRep) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{66} }

func (m *MsgTableInfoRep) GetTableInfo() *TableFaceInfo {
	if m != nil {
		return m.TableInfo
	}
	return nil
}

// 座位信息
type MsgSeatInfoRep struct {
	Players          []*SeatInfo `protobuf:"bytes,1,rep,name=players" json:"players,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *MsgSeatInfoRep) Reset()                    { *m = MsgSeatInfoRep{} }
func (m *MsgSeatInfoRep) String() string            { return proto.CompactTextString(m) }
func (*MsgSeatInfoRep) ProtoMessage()               {}
func (*MsgSeatInfoRep) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{67} }

func (m *MsgSeatInfoRep) GetPlayers() []*SeatInfo {
	if m != nil {
		return m.Players
	}
	return nil
}

// 桌子准备
type MsgTableReadyReq struct {
	Ready            *uint32 `protobuf:"varint,1,opt,name=ready" json:"ready,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgTableReadyReq) Reset()                    { *m = MsgTableReadyReq{} }
func (m *MsgTableReadyReq) String() string            { return proto.CompactTextString(m) }
func (*MsgTableReadyReq) ProtoMessage()               {}
func (*MsgTableReadyReq) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{68} }

func (m *MsgTableReadyReq) GetReady() uint32 {
	if m != nil && m.Ready != nil {
		return *m.Ready
	}
	return 0
}

type MsgTableReadyRep struct {
	Readys           []uint32 `protobuf:"varint,1,rep,name=readys" json:"readys,omitempty"`
	AutoStates       []uint32 `protobuf:"varint,2,rep,name=auto_states" json:"auto_states,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *MsgTableReadyRep) Reset()                    { *m = MsgTableReadyRep{} }
func (m *MsgTableReadyRep) String() string            { return proto.CompactTextString(m) }
func (*MsgTableReadyRep) ProtoMessage()               {}
func (*MsgTableReadyRep) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{69} }

func (m *MsgTableReadyRep) GetReadys() []uint32 {
	if m != nil {
		return m.Readys
	}
	return nil
}

func (m *MsgTableReadyRep) GetAutoStates() []uint32 {
	if m != nil {
		return m.AutoStates
	}
	return nil
}

// 桌子聊天
type MsgTableChatReq struct {
	ChatMsg          []byte `protobuf:"bytes,1,opt,name=chat_msg" json:"chat_msg,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgTableChatReq) Reset()                    { *m = MsgTableChatReq{} }
func (m *MsgTableChatReq) String() string            { return proto.CompactTextString(m) }
func (*MsgTableChatReq) ProtoMessage()               {}
func (*MsgTableChatReq) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{70} }

func (m *MsgTableChatReq) GetChatMsg() []byte {
	if m != nil {
		return m.ChatMsg
	}
	return nil
}

type MsgTableChatRep struct {
	Uid              *uint32 `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	ChatMsg          []byte  `protobuf:"bytes,2,opt,name=chat_msg" json:"chat_msg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgTableChatRep) Reset()                    { *m = MsgTableChatRep{} }
func (m *MsgTableChatRep) String() string            { return proto.CompactTextString(m) }
func (*MsgTableChatRep) ProtoMessage()               {}
func (*MsgTableChatRep) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{71} }

func (m *MsgTableChatRep) GetUid() uint32 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *MsgTableChatRep) GetChatMsg() []byte {
	if m != nil {
		return m.ChatMsg
	}
	return nil
}

//  托管
type MsgTableSetAutoReq struct {
	AutoType         *uint32 `protobuf:"varint,1,opt,name=auto_type" json:"auto_type,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgTableSetAutoReq) Reset()                    { *m = MsgTableSetAutoReq{} }
func (m *MsgTableSetAutoReq) String() string            { return proto.CompactTextString(m) }
func (*MsgTableSetAutoReq) ProtoMessage()               {}
func (*MsgTableSetAutoReq) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{72} }

func (m *MsgTableSetAutoReq) GetAutoType() uint32 {
	if m != nil && m.AutoType != nil {
		return *m.AutoType
	}
	return 0
}

type MsgTableSetAutoRep struct {
	Result           *uint32 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	AutoState        *uint32 `protobuf:"varint,2,opt,name=auto_state" json:"auto_state,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgTableSetAutoRep) Reset()                    { *m = MsgTableSetAutoRep{} }
func (m *MsgTableSetAutoRep) String() string            { return proto.CompactTextString(m) }
func (*MsgTableSetAutoRep) ProtoMessage()               {}
func (*MsgTableSetAutoRep) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{73} }

func (m *MsgTableSetAutoRep) GetResult() uint32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *MsgTableSetAutoRep) GetAutoState() uint32 {
	if m != nil && m.AutoState != nil {
		return *m.AutoState
	}
	return 0
}

type MsgFastJoinRoomReq struct {
	Deal             *uint32 `protobuf:"varint,1,opt,name=deal" json:"deal,omitempty"`
	Consume          *uint32 `protobuf:"varint,2,opt,name=consume" json:"consume,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgFastJoinRoomReq) Reset()                    { *m = MsgFastJoinRoomReq{} }
func (m *MsgFastJoinRoomReq) String() string            { return proto.CompactTextString(m) }
func (*MsgFastJoinRoomReq) ProtoMessage()               {}
func (*MsgFastJoinRoomReq) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{74} }

func (m *MsgFastJoinRoomReq) GetDeal() uint32 {
	if m != nil && m.Deal != nil {
		return *m.Deal
	}
	return 0
}

func (m *MsgFastJoinRoomReq) GetConsume() uint32 {
	if m != nil && m.Consume != nil {
		return *m.Consume
	}
	return 0
}

type MsgFastJoinRoomRep struct {
	Result           *uint32 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgFastJoinRoomRep) Reset()                    { *m = MsgFastJoinRoomRep{} }
func (m *MsgFastJoinRoomRep) String() string            { return proto.CompactTextString(m) }
func (*MsgFastJoinRoomRep) ProtoMessage()               {}
func (*MsgFastJoinRoomRep) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{75} }

func (m *MsgFastJoinRoomRep) GetResult() uint32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

type MsgFastJoinTableReq struct {
	TableId          *uint32 `protobuf:"varint,1,opt,name=table_id" json:"table_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgFastJoinTableReq) Reset()                    { *m = MsgFastJoinTableReq{} }
func (m *MsgFastJoinTableReq) String() string            { return proto.CompactTextString(m) }
func (*MsgFastJoinTableReq) ProtoMessage()               {}
func (*MsgFastJoinTableReq) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{76} }

func (m *MsgFastJoinTableReq) GetTableId() uint32 {
	if m != nil && m.TableId != nil {
		return *m.TableId
	}
	return 0
}

type MsgFastJoinTableRep struct {
	Result           *uint32 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgFastJoinTableRep) Reset()                    { *m = MsgFastJoinTableRep{} }
func (m *MsgFastJoinTableRep) String() string            { return proto.CompactTextString(m) }
func (*MsgFastJoinTableRep) ProtoMessage()               {}
func (*MsgFastJoinTableRep) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{77} }

func (m *MsgFastJoinTableRep) GetResult() uint32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

// 查看桌子信息
type MsgQueryTableListReq struct {
	Startid          *uint32 `protobuf:"varint,1,opt,name=startid" json:"startid,omitempty"`
	Endid            *uint32 `protobuf:"varint,2,opt,name=endid" json:"endid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgQueryTableListReq) Reset()                    { *m = MsgQueryTableListReq{} }
func (m *MsgQueryTableListReq) String() string            { return proto.CompactTextString(m) }
func (*MsgQueryTableListReq) ProtoMessage()               {}
func (*MsgQueryTableListReq) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{78} }

func (m *MsgQueryTableListReq) GetStartid() uint32 {
	if m != nil && m.Startid != nil {
		return *m.Startid
	}
	return 0
}

func (m *MsgQueryTableListReq) GetEndid() uint32 {
	if m != nil && m.Endid != nil {
		return *m.Endid
	}
	return 0
}

// 桌子列表
type MsgQueryTableListRep struct {
	Tables           []*TableFaceInfo `protobuf:"bytes,1,rep,name=tables" json:"tables,omitempty"`
	TableNum         *uint32          `protobuf:"varint,2,opt,name=table_num" json:"table_num,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *MsgQueryTableListRep) Reset()                    { *m = MsgQueryTableListRep{} }
func (m *MsgQueryTableListRep) String() string            { return proto.CompactTextString(m) }
func (*MsgQueryTableListRep) ProtoMessage()               {}
func (*MsgQueryTableListRep) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{79} }

func (m *MsgQueryTableListRep) GetTables() []*TableFaceInfo {
	if m != nil {
		return m.Tables
	}
	return nil
}

func (m *MsgQueryTableListRep) GetTableNum() uint32 {
	if m != nil && m.TableNum != nil {
		return *m.TableNum
	}
	return 0
}

// 玩家信息变更
type MsgNotifyPlayerJoinRep struct {
	JoinLeave        *uint32     `protobuf:"varint,1,opt,name=join_leave" json:"join_leave,omitempty"`
	Player           *LookerInfo `protobuf:"bytes,2,opt,name=player" json:"player,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *MsgNotifyPlayerJoinRep) Reset()                    { *m = MsgNotifyPlayerJoinRep{} }
func (m *MsgNotifyPlayerJoinRep) String() string            { return proto.CompactTextString(m) }
func (*MsgNotifyPlayerJoinRep) ProtoMessage()               {}
func (*MsgNotifyPlayerJoinRep) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{80} }

func (m *MsgNotifyPlayerJoinRep) GetJoinLeave() uint32 {
	if m != nil && m.JoinLeave != nil {
		return *m.JoinLeave
	}
	return 0
}

func (m *MsgNotifyPlayerJoinRep) GetPlayer() *LookerInfo {
	if m != nil {
		return m.Player
	}
	return nil
}

// 座位信息
type MsgLookerListInfoRep struct {
	Lookers          []*LookerInfo `protobuf:"bytes,1,rep,name=lookers" json:"lookers,omitempty"`
	IsReset          *uint32       `protobuf:"varint,2,opt,name=is_reset" json:"is_reset,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *MsgLookerListInfoRep) Reset()                    { *m = MsgLookerListInfoRep{} }
func (m *MsgLookerListInfoRep) String() string            { return proto.CompactTextString(m) }
func (*MsgLookerListInfoRep) ProtoMessage()               {}
func (*MsgLookerListInfoRep) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{81} }

func (m *MsgLookerListInfoRep) GetLookers() []*LookerInfo {
	if m != nil {
		return m.Lookers
	}
	return nil
}

func (m *MsgLookerListInfoRep) GetIsReset() uint32 {
	if m != nil && m.IsReset != nil {
		return *m.IsReset
	}
	return 0
}

// 玩家坐下或者站起
type MsgSitdownStandupReq struct {
	OperId           *uint32 `protobuf:"varint,1,opt,name=oper_id" json:"oper_id,omitempty"`
	ChairId          *uint32 `protobuf:"varint,2,opt,name=chair_id" json:"chair_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgSitdownStandupReq) Reset()                    { *m = MsgSitdownStandupReq{} }
func (m *MsgSitdownStandupReq) String() string            { return proto.CompactTextString(m) }
func (*MsgSitdownStandupReq) ProtoMessage()               {}
func (*MsgSitdownStandupReq) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{82} }

func (m *MsgSitdownStandupReq) GetOperId() uint32 {
	if m != nil && m.OperId != nil {
		return *m.OperId
	}
	return 0
}

func (m *MsgSitdownStandupReq) GetChairId() uint32 {
	if m != nil && m.ChairId != nil {
		return *m.ChairId
	}
	return 0
}

type MsgSitdownStandupRep struct {
	OperId           *uint32 `protobuf:"varint,1,opt,name=oper_id" json:"oper_id,omitempty"`
	ChairId          *uint32 `protobuf:"varint,2,opt,name=chair_id" json:"chair_id,omitempty"`
	Result           *uint32 `protobuf:"varint,3,opt,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgSitdownStandupRep) Reset()                    { *m = MsgSitdownStandupRep{} }
func (m *MsgSitdownStandupRep) String() string            { return proto.CompactTextString(m) }
func (*MsgSitdownStandupRep) ProtoMessage()               {}
func (*MsgSitdownStandupRep) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{83} }

func (m *MsgSitdownStandupRep) GetOperId() uint32 {
	if m != nil && m.OperId != nil {
		return *m.OperId
	}
	return 0
}

func (m *MsgSitdownStandupRep) GetChairId() uint32 {
	if m != nil && m.ChairId != nil {
		return *m.ChairId
	}
	return 0
}

func (m *MsgSitdownStandupRep) GetResult() uint32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

// 私人房请求结束游戏或者投票表决
type MsgPrivateGameoverReq struct {
	Reason           *uint32 `protobuf:"varint,1,opt,name=reason" json:"reason,omitempty"`
	IsAgree          *uint32 `protobuf:"varint,2,opt,name=is_agree" json:"is_agree,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgPrivateGameoverReq) Reset()                    { *m = MsgPrivateGameoverReq{} }
func (m *MsgPrivateGameoverReq) String() string            { return proto.CompactTextString(m) }
func (*MsgPrivateGameoverReq) ProtoMessage()               {}
func (*MsgPrivateGameoverReq) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{84} }

func (m *MsgPrivateGameoverReq) GetReason() uint32 {
	if m != nil && m.Reason != nil {
		return *m.Reason
	}
	return 0
}

func (m *MsgPrivateGameoverReq) GetIsAgree() uint32 {
	if m != nil && m.IsAgree != nil {
		return *m.IsAgree
	}
	return 0
}

type MsgPrivateGameoverResp struct {
	ReqId            *uint32  `protobuf:"varint,1,opt,name=req_id" json:"req_id,omitempty"`
	Reason           *uint32  `protobuf:"varint,2,opt,name=reason" json:"reason,omitempty"`
	AgreeState       []uint32 `protobuf:"varint,3,rep,name=agree_state" json:"agree_state,omitempty"`
	LeftTime         *uint32  `protobuf:"varint,4,opt,name=left_time" json:"left_time,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *MsgPrivateGameoverResp) Reset()                    { *m = MsgPrivateGameoverResp{} }
func (m *MsgPrivateGameoverResp) String() string            { return proto.CompactTextString(m) }
func (*MsgPrivateGameoverResp) ProtoMessage()               {}
func (*MsgPrivateGameoverResp) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{85} }

func (m *MsgPrivateGameoverResp) GetReqId() uint32 {
	if m != nil && m.ReqId != nil {
		return *m.ReqId
	}
	return 0
}

func (m *MsgPrivateGameoverResp) GetReason() uint32 {
	if m != nil && m.Reason != nil {
		return *m.Reason
	}
	return 0
}

func (m *MsgPrivateGameoverResp) GetAgreeState() []uint32 {
	if m != nil {
		return m.AgreeState
	}
	return nil
}

func (m *MsgPrivateGameoverResp) GetLeftTime() uint32 {
	if m != nil && m.LeftTime != nil {
		return *m.LeftTime
	}
	return 0
}

// 私人房实时战绩请求
type MsgPrivatePlayInfoReq struct {
	Reqid            *uint32 `protobuf:"varint,1,opt,name=reqid" json:"reqid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgPrivatePlayInfoReq) Reset()                    { *m = MsgPrivatePlayInfoReq{} }
func (m *MsgPrivatePlayInfoReq) String() string            { return proto.CompactTextString(m) }
func (*MsgPrivatePlayInfoReq) ProtoMessage()               {}
func (*MsgPrivatePlayInfoReq) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{86} }

func (m *MsgPrivatePlayInfoReq) GetReqid() uint32 {
	if m != nil && m.Reqid != nil {
		return *m.Reqid
	}
	return 0
}

type MsgPrivatePlayInfoResp struct {
	UserInfo         []*PlayerGameInfo `protobuf:"bytes,1,rep,name=user_info" json:"user_info,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *MsgPrivatePlayInfoResp) Reset()                    { *m = MsgPrivatePlayInfoResp{} }
func (m *MsgPrivatePlayInfoResp) String() string            { return proto.CompactTextString(m) }
func (*MsgPrivatePlayInfoResp) ProtoMessage()               {}
func (*MsgPrivatePlayInfoResp) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{87} }

func (m *MsgPrivatePlayInfoResp) GetUserInfo() []*PlayerGameInfo {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

// 座位信息
type MsgSeatValueInfoRep struct {
	Players          []*SeatValueInfo `protobuf:"bytes,1,rep,name=players" json:"players,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *MsgSeatValueInfoRep) Reset()                    { *m = MsgSeatValueInfoRep{} }
func (m *MsgSeatValueInfoRep) String() string            { return proto.CompactTextString(m) }
func (*MsgSeatValueInfoRep) ProtoMessage()               {}
func (*MsgSeatValueInfoRep) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{88} }

func (m *MsgSeatValueInfoRep) GetPlayers() []*SeatValueInfo {
	if m != nil {
		return m.Players
	}
	return nil
}

// 大厅进入私人房请求
type MsgEnterPrivateTableReq struct {
	Passwd           *string `protobuf:"bytes,1,opt,name=passwd" json:"passwd,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgEnterPrivateTableReq) Reset()                    { *m = MsgEnterPrivateTableReq{} }
func (m *MsgEnterPrivateTableReq) String() string            { return proto.CompactTextString(m) }
func (*MsgEnterPrivateTableReq) ProtoMessage()               {}
func (*MsgEnterPrivateTableReq) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{89} }

func (m *MsgEnterPrivateTableReq) GetPasswd() string {
	if m != nil && m.Passwd != nil {
		return *m.Passwd
	}
	return ""
}

type MsgEnterPrivateTableResp struct {
	RetCode          *uint32 `protobuf:"varint,1,opt,name=ret_code" json:"ret_code,omitempty"`
	Svrid            *uint32 `protobuf:"varint,2,opt,name=svrid" json:"svrid,omitempty"`
	Roomid           *uint32 `protobuf:"varint,3,opt,name=roomid" json:"roomid,omitempty"`
	TableId          *uint32 `protobuf:"varint,4,opt,name=table_id" json:"table_id,omitempty"`
	Passwd           *string `protobuf:"bytes,5,opt,name=passwd" json:"passwd,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgEnterPrivateTableResp) Reset()                    { *m = MsgEnterPrivateTableResp{} }
func (m *MsgEnterPrivateTableResp) String() string            { return proto.CompactTextString(m) }
func (*MsgEnterPrivateTableResp) ProtoMessage()               {}
func (*MsgEnterPrivateTableResp) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{90} }

func (m *MsgEnterPrivateTableResp) GetRetCode() uint32 {
	if m != nil && m.RetCode != nil {
		return *m.RetCode
	}
	return 0
}

func (m *MsgEnterPrivateTableResp) GetSvrid() uint32 {
	if m != nil && m.Svrid != nil {
		return *m.Svrid
	}
	return 0
}

func (m *MsgEnterPrivateTableResp) GetRoomid() uint32 {
	if m != nil && m.Roomid != nil {
		return *m.Roomid
	}
	return 0
}

func (m *MsgEnterPrivateTableResp) GetTableId() uint32 {
	if m != nil && m.TableId != nil {
		return *m.TableId
	}
	return 0
}

func (m *MsgEnterPrivateTableResp) GetPasswd() string {
	if m != nil && m.Passwd != nil {
		return *m.Passwd
	}
	return ""
}

// 请求投票信息
type MsgVoteInfoReq struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgVoteInfoReq) Reset()                    { *m = MsgVoteInfoReq{} }
func (m *MsgVoteInfoReq) String() string            { return proto.CompactTextString(m) }
func (*MsgVoteInfoReq) ProtoMessage()               {}
func (*MsgVoteInfoReq) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{91} }

func init() {
	proto.RegisterType((*MsgHeartTest)(nil), "net.msg_heart_test")
	proto.RegisterType((*MsgLoginReq)(nil), "net.msg_login_req")
	proto.RegisterType((*MsgLoginRep)(nil), "net.msg_login_rep")
	proto.RegisterType((*MsgNotifyLeaveRep)(nil), "net.msg_notify_leave_rep")
	proto.RegisterType((*MsgEnterGameRep)(nil), "net.msg_enter_game_rep")
	proto.RegisterType((*MsgPlayerDataRep)(nil), "net.msg_player_data_rep")
	proto.RegisterType((*MsgUpdateAccValue)(nil), "net.msg_update_acc_value")
	proto.RegisterType((*MsgUpdateBaseValue)(nil), "net.msg_update_base_value")
	proto.RegisterType((*MsgUpdateLandInfo)(nil), "net.msg_update_land_info")
	proto.RegisterType((*MsgUpdateGameInfo)(nil), "net.msg_update_game_info")
	proto.RegisterType((*MsgSvrsInfoReq)(nil), "net.msg_svrs_info_req")
	proto.RegisterType((*MsgSvrsInfoRep)(nil), "net.msg_svrs_info_rep")
	proto.RegisterType((*MsgEnterGamesvrReq)(nil), "net.msg_enter_gamesvr_req")
	proto.RegisterType((*MsgEnterGamesvrRep)(nil), "net.msg_enter_gamesvr_rep")
	proto.RegisterType((*MsgLoginSafeboxReq)(nil), "net.msg_login_safebox_req")
	proto.RegisterType((*MsgLoginSafeboxRep)(nil), "net.msg_login_safebox_rep")
	proto.RegisterType((*MsgChangeSafeboxPwdReq)(nil), "net.msg_change_safebox_pwd_req")
	proto.RegisterType((*MsgChangeSafeboxPwdRep)(nil), "net.msg_change_safebox_pwd_rep")
	proto.RegisterType((*MsgTakeSafeboxReq)(nil), "net.msg_take_safebox_req")
	proto.RegisterType((*MsgTakeSafeboxRep)(nil), "net.msg_take_safebox_rep")
	proto.RegisterType((*MsgGiveSafeboxReq)(nil), "net.msg_give_safebox_req")
	proto.RegisterType((*MsgGiveSafeboxRep)(nil), "net.msg_give_safebox_rep")
	proto.RegisterType((*MsgPhpBroadcastRep)(nil), "net.msg_php_broadcast_rep")
	proto.RegisterType((*MsgSystemBroadcastRep)(nil), "net.msg_system_broadcast_rep")
	proto.RegisterType((*MsgSendAllMissionRep)(nil), "net.msg_send_all_mission_rep")
	proto.RegisterType((*MsgSendMissionRep)(nil), "net.msg_send_mission_rep")
	proto.RegisterType((*MsgGetMissionPrizeReq)(nil), "net.msg_get_mission_prize_req")
	proto.RegisterType((*MsgGetMissionPrizeRep)(nil), "net.msg_get_mission_prize_rep")
	proto.RegisterType((*MsgGetLoginRewardReq)(nil), "net.msg_get_login_reward_req")
	proto.RegisterType((*MsgGetLoginRewardRep)(nil), "net.msg_get_login_reward_rep")
	proto.RegisterType((*MsgGetBankruptHelpReq)(nil), "net.msg_get_bankrupt_help_req")
	proto.RegisterType((*MsgGetBankruptHelpRep)(nil), "net.msg_get_bankrupt_help_rep")
	proto.RegisterType((*MsgExchangeScoreReq)(nil), "net.msg_exchange_score_req")
	proto.RegisterType((*MsgExchangeScoreRep)(nil), "net.msg_exchange_score_rep")
	proto.RegisterType((*MsgSpeakBroadcastReq)(nil), "net.msg_speak_broadcast_req")
	proto.RegisterType((*MsgSpeakBroadcastRep)(nil), "net.msg_speak_broadcast_rep")
	proto.RegisterType((*MsgGetHistorySpeak)(nil), "net.msg_get_history_speak")
	proto.RegisterType((*MsgSendHistorySpeak)(nil), "net.msg_send_history_speak")
	proto.RegisterType((*MsgSpeakOperRep)(nil), "net.msg_speak_oper_rep")
	proto.RegisterType((*MsgGetServerInfo)(nil), "net.msg_get_server_info")
	proto.RegisterType((*ServerInfo)(nil), "net.server_info")
	proto.RegisterType((*MsgSendServerInfo)(nil), "net.msg_send_server_info")
	proto.RegisterType((*MsgPrivateGameInfoReq)(nil), "net.msg_private_game_info_req")
	proto.RegisterType((*MsgPrivateGameInfoRep)(nil), "net.msg_private_game_info_rep")
	proto.RegisterType((*MsgPrivateGameResult)(nil), "net.msg_private_game_result")
	proto.RegisterType((*MsgSelfPrivateListReq)(nil), "net.msg_self_private_list_req")
	proto.RegisterType((*MsgSelfPrivateListRep)(nil), "net.msg_self_private_list_rep")
	proto.RegisterType((*MsgRoomsInfoReq)(nil), "net.msg_rooms_info_req")
	proto.RegisterType((*MsgRoomsInfoRep)(nil), "net.msg_rooms_info_rep")
	proto.RegisterType((*MsgBackLobbyReq)(nil), "net.msg_back_lobby_req")
	proto.RegisterType((*MsgBackLobbyRep)(nil), "net.msg_back_lobby_rep")
	proto.RegisterType((*MsgGotoGamesvrReq)(nil), "net.msg_goto_gamesvr_req")
	proto.RegisterType((*MsgGotoGamesvrRep)(nil), "net.msg_goto_gamesvr_rep")
	proto.RegisterType((*MsgEnterRoomReq)(nil), "net.msg_enter_room_req")
	proto.RegisterType((*MsgEnterRoomRep)(nil), "net.msg_enter_room_rep")
	proto.RegisterType((*MsgNotifyLeaveRoomRep)(nil), "net.msg_notify_leave_room_rep")
	proto.RegisterType((*MsgTableListReq)(nil), "net.msg_table_list_req")
	proto.RegisterType((*MsgTableListRep)(nil), "net.msg_table_list_rep")
	proto.RegisterType((*MsgCreateTableReq)(nil), "net.msg_create_table_req")
	proto.RegisterType((*MsgCreateTableRep)(nil), "net.msg_create_table_rep")
	proto.RegisterType((*MsgRenewTableReq)(nil), "net.msg_renew_table_req")
	proto.RegisterType((*MsgRenewTableRep)(nil), "net.msg_renew_table_rep")
	proto.RegisterType((*MsgLeaveTableReq)(nil), "net.msg_leave_table_req")
	proto.RegisterType((*MsgLeaveTableRep)(nil), "net.msg_leave_table_rep")
	proto.RegisterType((*MsgEnterTableReq)(nil), "net.msg_enter_table_req")
	proto.RegisterType((*MsgEnterTableRep)(nil), "net.msg_enter_table_rep")
	proto.RegisterType((*MsgTableInfoRep)(nil), "net.msg_table_info_rep")
	proto.RegisterType((*MsgSeatInfoRep)(nil), "net.msg_seat_info_rep")
	proto.RegisterType((*MsgTableReadyReq)(nil), "net.msg_table_ready_req")
	proto.RegisterType((*MsgTableReadyRep)(nil), "net.msg_table_ready_rep")
	proto.RegisterType((*MsgTableChatReq)(nil), "net.msg_table_chat_req")
	proto.RegisterType((*MsgTableChatRep)(nil), "net.msg_table_chat_rep")
	proto.RegisterType((*MsgTableSetAutoReq)(nil), "net.msg_table_set_auto_req")
	proto.RegisterType((*MsgTableSetAutoRep)(nil), "net.msg_table_set_auto_rep")
	proto.RegisterType((*MsgFastJoinRoomReq)(nil), "net.msg_fast_join_room_req")
	proto.RegisterType((*MsgFastJoinRoomRep)(nil), "net.msg_fast_join_room_rep")
	proto.RegisterType((*MsgFastJoinTableReq)(nil), "net.msg_fast_join_table_req")
	proto.RegisterType((*MsgFastJoinTableRep)(nil), "net.msg_fast_join_table_rep")
	proto.RegisterType((*MsgQueryTableListReq)(nil), "net.msg_query_table_list_req")
	proto.RegisterType((*MsgQueryTableListRep)(nil), "net.msg_query_table_list_rep")
	proto.RegisterType((*MsgNotifyPlayerJoinRep)(nil), "net.msg_notify_player_join_rep")
	proto.RegisterType((*MsgLookerListInfoRep)(nil), "net.msg_looker_list_info_rep")
	proto.RegisterType((*MsgSitdownStandupReq)(nil), "net.msg_sitdown_standup_req")
	proto.RegisterType((*MsgSitdownStandupRep)(nil), "net.msg_sitdown_standup_rep")
	proto.RegisterType((*MsgPrivateGameoverReq)(nil), "net.msg_private_gameover_req")
	proto.RegisterType((*MsgPrivateGameoverResp)(nil), "net.msg_private_gameover_resp")
	proto.RegisterType((*MsgPrivatePlayInfoReq)(nil), "net.msg_private_play_info_req")
	proto.RegisterType((*MsgPrivatePlayInfoResp)(nil), "net.msg_private_play_info_resp")
	proto.RegisterType((*MsgSeatValueInfoRep)(nil), "net.msg_seat_value_info_rep")
	proto.RegisterType((*MsgEnterPrivateTableReq)(nil), "net.msg_enter_private_table_req")
	proto.RegisterType((*MsgEnterPrivateTableResp)(nil), "net.msg_enter_private_table_resp")
	proto.RegisterType((*MsgVoteInfoReq)(nil), "net.msg_vote_info_req")
}

func init() { proto.RegisterFile("client_logic_msg.proto", fileDescriptor14) }

var fileDescriptor14 = []byte{
	// 1821 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x58, 0x7b, 0x6f, 0xdb, 0xc8,
	0x11, 0x87, 0x2d, 0xf9, 0xa1, 0xb1, 0xe5, 0xd8, 0xf4, 0xe3, 0xd4, 0x5c, 0x8a, 0xda, 0x6c, 0x9c,
	0xb3, 0xef, 0x7a, 0x0e, 0x90, 0xa6, 0x4d, 0x9b, 0x04, 0x49, 0x80, 0x06, 0x45, 0x91, 0x14, 0x28,
	0xd0, 0x36, 0xed, 0x9f, 0xc4, 0x8a, 0x5c, 0xc9, 0xac, 0x28, 0x2e, 0xbd, 0xbb, 0x92, 0xa3, 0x7e,
	0x84, 0x7e, 0x91, 0x7e, 0xcd, 0x62, 0x66, 0x96, 0x2f, 0x93, 0x74, 0x7d, 0xff, 0x89, 0xc3, 0x79,
	0xed, 0xec, 0x6f, 0x66, 0x7e, 0x14, 0x9c, 0x84, 0x49, 0x2c, 0x53, 0x1b, 0x24, 0x6a, 0x1a, 0x87,
	0xc1, 0xdc, 0x4c, 0xaf, 0x32, 0xad, 0xac, 0xf2, 0x7a, 0xa9, 0xb4, 0x8f, 0x8f, 0xc7, 0xc2, 0x48,
	0x14, 0x06, 0xc6, 0xea, 0x45, 0x68, 0xf9, 0xdd, 0xe3, 0x7d, 0xa9, 0xb5, 0xd2, 0x41, 0xa8, 0x22,
	0xc9, 0x12, 0xdf, 0x87, 0x3d, 0xd4, 0xba, 0x96, 0x42, 0xdb, 0xc0, 0x4a, 0x63, 0xbd, 0x7d, 0xd8,
	0x36, 0x4b, 0x1d, 0xd8, 0x78, 0x2e, 0x47, 0x6b, 0xa7, 0x6b, 0x17, 0x43, 0xff, 0x0d, 0x0c, 0x51,
	0x07, 0x03, 0xa5, 0x81, 0x96, 0x37, 0xde, 0x0e, 0xf4, 0x16, 0x71, 0xc4, 0x6f, 0xf1, 0x61, 0x26,
	0x57, 0xa3, 0xf5, 0xd3, 0xb5, 0x8b, 0x5d, 0x34, 0x8e, 0xe4, 0x32, 0x0e, 0x65, 0x1c, 0x8d, 0x7a,
	0x28, 0xf1, 0x5f, 0xd6, 0x8d, 0x33, 0x6f, 0x0f, 0x36, 0xb5, 0x34, 0x8b, 0xc4, 0x3a, 0xfb, 0x43,
	0xd8, 0x31, 0x52, 0x2f, 0xa5, 0x0b, 0xb9, 0x4e, 0x21, 0x9f, 0xc1, 0x11, 0x5a, 0xa5, 0xca, 0xc6,
	0x93, 0x55, 0x90, 0x48, 0xb1, 0x94, 0x6d, 0xc6, 0xfe, 0x53, 0xf0, 0x50, 0x4f, 0xa6, 0x56, 0xea,
	0x60, 0x2a, 0xe6, 0xed, 0x5a, 0xbf, 0x83, 0x43, 0xd4, 0xca, 0x12, 0xb1, 0x92, 0x3a, 0x88, 0x84,
	0x15, 0xa4, 0x76, 0x06, 0x03, 0x2a, 0x13, 0x0a, 0x48, 0x73, 0xe7, 0xc5, 0xde, 0x55, 0x2a, 0xed,
	0x15, 0x49, 0xe3, 0x74, 0xa2, 0xfc, 0x25, 0xe7, 0xb1, 0xc8, 0x22, 0x61, 0x65, 0x20, 0xc2, 0x30,
	0x58, 0x8a, 0x64, 0x21, 0xbd, 0x47, 0xb0, 0x15, 0xc5, 0x62, 0xae, 0x52, 0xae, 0x42, 0xcf, 0xdb,
	0x85, 0x7e, 0xa8, 0xe2, 0x94, 0xd2, 0xef, 0x79, 0x43, 0xd8, 0x30, 0xa1, 0xd2, 0x92, 0x6a, 0x40,
	0x8f, 0x71, 0x3a, 0x55, 0x76, 0xd4, 0xa7, 0xc7, 0x3d, 0xd8, 0x0c, 0xc9, 0xcd, 0x68, 0x83, 0x9e,
	0x0f, 0x60, 0x60, 0xc4, 0x44, 0x06, 0xe4, 0x60, 0x13, 0x45, 0xfe, 0x7f, 0xd6, 0xe0, 0xb8, 0x12,
	0x98, 0x12, 0xe2, 0xc8, 0x47, 0xb0, 0x8b, 0xca, 0x63, 0xf5, 0xd5, 0x58, 0x61, 0xdd, 0x15, 0x91,
	0x4b, 0x2a, 0x31, 0xd7, 0x0f, 0x5d, 0xde, 0x4a, 0x39, 0x63, 0x51, 0x2f, 0x57, 0xd1, 0xf2, 0x56,
	0xe8, 0x88, 0xb2, 0x18, 0xe2, 0x55, 0x8d, 0x45, 0x3a, 0xd3, 0x8b, 0xcc, 0x52, 0x1e, 0x43, 0xef,
	0x04, 0xf6, 0x22, 0xb1, 0xe2, 0x32, 0x86, 0x6a, 0x91, 0x5a, 0x4a, 0x66, 0xe8, 0xff, 0xbe, 0x56,
	0x84, 0x44, 0xa4, 0x11, 0x15, 0x07, 0xeb, 0x47, 0x0f, 0x8d, 0xfa, 0x15, 0x2a, 0x77, 0x4c, 0xc9,
	0xb3, 0x33, 0xed, 0x57, 0xac, 0x0e, 0xc9, 0x8a, 0xde, 0xd2, 0xe5, 0x90, 0xe9, 0x33, 0x38, 0x20,
	0xfc, 0x2e, 0xb5, 0x21, 0x01, 0x21, 0xef, 0x00, 0x06, 0xa4, 0x66, 0x57, 0x59, 0x8e, 0xce, 0x3f,
	0x34, 0xf5, 0x32, 0xef, 0x5b, 0xe8, 0xa3, 0x60, 0xb4, 0x76, 0xda, 0xbb, 0xd8, 0x79, 0x31, 0x24,
	0xff, 0x88, 0x6a, 0x0a, 0x7e, 0x00, 0x83, 0x70, 0xa1, 0xd1, 0x22, 0x8e, 0x0a, 0xbc, 0x1d, 0xd7,
	0x71, 0x84, 0xca, 0x18, 0x10, 0x6f, 0x92, 0xf4, 0x38, 0xd8, 0x6f, 0xdb, 0xf5, 0x9a, 0xa8, 0x2e,
	0xec, 0xd8, 0xff, 0x77, 0x6c, 0xc7, 0x5d, 0xe0, 0xee, 0x8f, 0xfc, 0xef, 0xc1, 0x66, 0x26, 0x8c,
	0xb9, 0xe5, 0x00, 0xbb, 0x5d, 0x8a, 0x4d, 0x4c, 0xbf, 0x83, 0xc7, 0xa8, 0x18, 0x5e, 0x8b, 0x74,
	0x2a, 0x0b, 0xcd, 0xec, 0x36, 0x22, 0xb7, 0x8f, 0x60, 0x4b, 0x25, 0x11, 0x3e, 0xb2, 0x5f, 0x14,
	0xa4, 0xf2, 0x96, 0x04, 0xd4, 0xa9, 0xfe, 0xaf, 0xee, 0xb1, 0x6f, 0x46, 0xbb, 0xe4, 0x7b, 0xb4,
	0x62, 0x26, 0x6b, 0xe9, 0x1f, 0xc0, 0x80, 0x64, 0x04, 0x5d, 0xea, 0x84, 0xfc, 0xca, 0xef, 0xa8,
	0x66, 0x2d, 0xaa, 0x95, 0x28, 0xeb, 0x6e, 0xd0, 0x90, 0xe9, 0x34, 0x5e, 0xd6, 0xa3, 0xec, 0xc3,
	0x36, 0xc9, 0xca, 0xa1, 0x83, 0x38, 0x40, 0x49, 0xd9, 0x73, 0xfe, 0xe7, 0x56, 0xe3, 0xec, 0x41,
	0xc6, 0x95, 0x4c, 0x7a, 0x6e, 0xae, 0xd0, 0x35, 0x64, 0xd7, 0x59, 0x30, 0xd6, 0x4a, 0x44, 0xa1,
	0x30, 0x96, 0xbc, 0xed, 0x40, 0x6f, 0x6e, 0xa6, 0xc5, 0x65, 0x8d, 0x08, 0x7a, 0x2b, 0x63, 0xe5,
	0xfc, 0x3e, 0xc5, 0xf7, 0x4e, 0x51, 0xa6, 0x51, 0x20, 0x92, 0x24, 0x98, 0xc7, 0xc6, 0xc4, 0x8a,
	0xe7, 0xe1, 0x2f, 0x61, 0xdb, 0x3d, 0xe6, 0x70, 0x3d, 0x20, 0xb8, 0xe6, 0x3a, 0xd8, 0x11, 0xfe,
	0x6b, 0x3e, 0x1c, 0x39, 0xa8, 0x1a, 0xfb, 0xb0, 0xe5, 0x1e, 0x5d, 0x2b, 0xb5, 0xd8, 0x5e, 0xc2,
	0xcf, 0xa8, 0x30, 0xd2, 0x16, 0xa6, 0x99, 0x8e, 0xff, 0x2d, 0xa9, 0xb4, 0xbb, 0xd0, 0x9f, 0x9b,
	0x02, 0xde, 0x37, 0xdd, 0xaa, 0x4d, 0x88, 0x57, 0x62, 0xaf, 0x77, 0xc4, 0xf6, 0x4e, 0x71, 0xc8,
	0x18, 0x89, 0x6d, 0x47, 0x95, 0x6d, 0x4e, 0xd8, 0xe7, 0x5c, 0x1a, 0x0c, 0x99, 0xef, 0x08, 0x1c,
	0x52, 0x94, 0xdc, 0x21, 0xec, 0xb8, 0xa7, 0x49, 0x22, 0xa6, 0x2e, 0xc7, 0xf7, 0x9d, 0x06, 0x59,
	0xab, 0x41, 0x03, 0x65, 0xcf, 0xcb, 0x43, 0xe6, 0x03, 0x30, 0xb8, 0x96, 0x49, 0x46, 0x21, 0x3d,
	0x00, 0xfa, 0xcd, 0xf3, 0x2f, 0x9f, 0x30, 0x9d, 0x06, 0xcd, 0xaa, 0x9c, 0xc0, 0x5e, 0xa1, 0xc4,
	0x4e, 0x38, 0xea, 0x47, 0x38, 0xa1, 0xc9, 0xf1, 0x35, 0xef, 0x38, 0xdc, 0x0f, 0x14, 0xf2, 0x18,
	0x86, 0x85, 0xb4, 0x9c, 0x6b, 0x78, 0x96, 0x42, 0x5c, 0xcc, 0x91, 0xbf, 0x77, 0x78, 0xc9, 0x7e,
	0x8a, 0x97, 0x06, 0xda, 0x9f, 0xc1, 0x37, 0x84, 0xae, 0x4c, 0x8a, 0x59, 0x0d, 0xc6, 0x37, 0x75,
	0x18, 0x7f, 0xea, 0xd2, 0xcb, 0x70, 0xbe, 0x10, 0x38, 0xab, 0x4d, 0x46, 0x82, 0x54, 0xb8, 0xa5,
	0xbe, 0x9b, 0xfb, 0x62, 0x5e, 0x70, 0xc9, 0x1d, 0x86, 0x45, 0xbd, 0x8e, 0x8d, 0x55, 0x7a, 0xc5,
	0x7e, 0xa9, 0x5f, 0xa5, 0xad, 0xf2, 0x0f, 0x57, 0x3a, 0x72, 0x57, 0xd7, 0xfd, 0x1e, 0xd1, 0x3b,
	0xcd, 0xfb, 0xe6, 0x09, 0xe3, 0xaf, 0x3d, 0x43, 0xff, 0x25, 0x53, 0x05, 0x7e, 0xa5, 0x32, 0xd9,
	0x3e, 0xb7, 0x71, 0x91, 0x46, 0x15, 0x22, 0x72, 0xcc, 0xd4, 0x01, 0x33, 0x72, 0x2c, 0x85, 0x50,
	0xfb, 0x8f, 0x82, 0xb4, 0xd0, 0x46, 0xa9, 0x6f, 0x09, 0x04, 0x91, 0xe3, 0x1a, 0xe9, 0x62, 0x5e,
	0x6e, 0x64, 0xad, 0xc6, 0xca, 0x92, 0xa8, 0x57, 0xcc, 0xa1, 0x62, 0x99, 0xf5, 0xab, 0xab, 0x96,
	0x8e, 0x5a, 0x0d, 0x70, 0x86, 0xe5, 0xc5, 0xc7, 0xfc, 0xac, 0xfb, 0xbc, 0xd2, 0x2a, 0x29, 0x7d,
	0x60, 0x94, 0x66, 0x3a, 0x5e, 0xd6, 0x76, 0x6d, 0xc7, 0xde, 0xa4, 0x3a, 0xa3, 0xa8, 0x48, 0xd1,
	0xff, 0xd2, 0xed, 0xa1, 0x59, 0xa8, 0x0b, 0x67, 0x9e, 0xa8, 0xe9, 0x68, 0x9d, 0x52, 0x3a, 0xa1,
	0x94, 0x1a, 0xd6, 0xfe, 0x47, 0x46, 0x4d, 0xed, 0x05, 0xbb, 0xf2, 0x2e, 0x5d, 0x5a, 0x34, 0x1f,
	0x78, 0x80, 0x75, 0x79, 0xb9, 0xe2, 0xe4, 0x8c, 0x4c, 0x26, 0x85, 0xab, 0x24, 0x76, 0x28, 0x6d,
	0xa1, 0x05, 0x9f, 0xba, 0xf5, 0x33, 0xef, 0x47, 0xd8, 0xcd, 0x65, 0x2e, 0x34, 0x1e, 0xe0, 0x9b,
	0x5a, 0x68, 0x2b, 0xc6, 0x89, 0x8b, 0xfd, 0x8a, 0xa1, 0xa3, 0x95, 0x9a, 0xdf, 0xcb, 0x45, 0xb0,
	0x48, 0xc4, 0x32, 0xf2, 0x76, 0xfd, 0x67, 0x8b, 0x61, 0xe6, 0xfd, 0x1c, 0x36, 0x48, 0xe2, 0xc2,
	0xf2, 0x44, 0x44, 0x09, 0xdf, 0xb5, 0x07, 0x80, 0xf4, 0x04, 0x05, 0xd5, 0x8e, 0x75, 0x8e, 0xb9,
	0x63, 0xcf, 0xd8, 0xf1, 0x58, 0x84, 0xb3, 0x20, 0x51, 0xe3, 0xf1, 0xaa, 0xc1, 0xcb, 0x73, 0x6a,
	0x5c, 0x53, 0x69, 0x2e, 0xf6, 0x73, 0xb7, 0x35, 0x95, 0x55, 0xf7, 0xf1, 0x9e, 0xdf, 0xb4, 0xaa,
	0xfd, 0x5f, 0xda, 0x73, 0x5e, 0xa5, 0xe7, 0x74, 0x42, 0x47, 0x4e, 0xf8, 0xb4, 0xb9, 0xf7, 0x2f,
	0x2d, 0x6a, 0x4d, 0xdf, 0x4f, 0xa0, 0x8f, 0xef, 0xdc, 0xb2, 0xb9, 0x5b, 0x35, 0x47, 0xea, 0xe8,
	0xd6, 0x5c, 0x91, 0xdc, 0xa0, 0xaf, 0x7f, 0x44, 0xe4, 0xde, 0x3d, 0x00, 0x96, 0x54, 0x30, 0xf3,
	0x9a, 0xf3, 0xe0, 0x9b, 0x2f, 0xc0, 0xb5, 0x0f, 0xdb, 0x0e, 0x0b, 0x95, 0xfe, 0x36, 0x52, 0x84,
	0xd7, 0x6c, 0xbb, 0xde, 0x69, 0x9b, 0x79, 0x4f, 0x61, 0x93, 0x24, 0xf9, 0x5d, 0x1f, 0x51, 0xd6,
	0xac, 0x34, 0x11, 0xa1, 0xc3, 0xd7, 0x7f, 0xd7, 0xb8, 0xbc, 0xa1, 0x96, 0x25, 0xf2, 0xdc, 0x76,
	0x8e, 0xa4, 0x48, 0xca, 0xb0, 0xb4, 0x37, 0xf9, 0xd3, 0x82, 0x89, 0x8b, 0x07, 0xa0, 0x32, 0x99,
	0x06, 0x5a, 0x2d, 0x52, 0x07, 0x0e, 0xfa, 0x82, 0x93, 0x82, 0x27, 0x4d, 0xbf, 0x1c, 0xc6, 0x3c,
	0x2a, 0x22, 0x47, 0xf6, 0xf1, 0x9b, 0xc4, 0x04, 0x42, 0x30, 0xc7, 0xf7, 0xce, 0x91, 0x87, 0x6a,
	0x31, 0x37, 0xa3, 0x2d, 0x4a, 0xf4, 0xb8, 0xd6, 0x0b, 0xb3, 0x65, 0x40, 0x6f, 0xfd, 0x3f, 0xb5,
	0x26, 0xda, 0xbc, 0xab, 0x6a, 0xcd, 0x0a, 0x04, 0x3b, 0xa2, 0xcb, 0xf3, 0xff, 0x0d, 0x0f, 0x56,
	0x2d, 0x91, 0x96, 0x96, 0x27, 0x6e, 0x2d, 0x36, 0x2b, 0x45, 0x62, 0x65, 0x5c, 0xb1, 0x3f, 0xb7,
	0x19, 0x67, 0x0f, 0x33, 0x6e, 0x6c, 0xbf, 0xef, 0xd8, 0x99, 0x43, 0x43, 0x77, 0x26, 0xfe, 0x79,
	0x9b, 0x62, 0xb3, 0xa5, 0x5e, 0xb1, 0x1a, 0xa3, 0xf9, 0xbe, 0x93, 0x95, 0x25, 0x61, 0x4a, 0xde,
	0x6a, 0x98, 0xb5, 0x1b, 0xd6, 0x18, 0xcd, 0xbb, 0x2a, 0xf6, 0x8a, 0x31, 0x73, 0x01, 0x50, 0x4a,
	0xdc, 0x74, 0x6d, 0xc7, 0xdf, 0x4b, 0xf7, 0x09, 0x85, 0xa0, 0x29, 0xcc, 0x7f, 0x01, 0x5b, 0xbc,
	0xc4, 0xea, 0x73, 0xaa, 0x50, 0xf2, 0x9f, 0x72, 0xba, 0x79, 0xa2, 0x22, 0x5a, 0xe5, 0x93, 0x83,
	0x1e, 0x8a, 0x9e, 0x6a, 0xd1, 0x72, 0x45, 0x13, 0xd1, 0x8a, 0x9d, 0x13, 0x4f, 0x11, 0x0b, 0xab,
	0x02, 0xfa, 0xa8, 0x35, 0xb4, 0x51, 0x90, 0x97, 0x54, 0xce, 0x15, 0x5e, 0x8b, 0xa2, 0x1f, 0xe9,
	0x77, 0xc9, 0x4b, 0x7e, 0xdd, 0xa2, 0x97, 0xd5, 0xff, 0xa5, 0xa8, 0x1a, 0x71, 0xb5, 0x7f, 0x60,
	0x56, 0xc1, 0x46, 0x46, 0xda, 0x80, 0xe2, 0xbb, 0xc1, 0x4e, 0xbf, 0x2b, 0x93, 0xe1, 0x6d, 0x87,
	0x72, 0x13, 0xf9, 0x1e, 0x40, 0x79, 0x10, 0x77, 0x3f, 0xaf, 0xd8, 0x7a, 0x82, 0x54, 0xe4, 0x5f,
	0x0a, 0x29, 0x6b, 0x3e, 0x0a, 0xeb, 0x0d, 0xfe, 0x08, 0xb6, 0x42, 0x95, 0x9a, 0x45, 0xc1, 0x3e,
	0x2e, 0x3a, 0x0c, 0x9b, 0xa0, 0xfb, 0x81, 0x97, 0x6c, 0xa9, 0x79, 0x1f, 0x90, 0x2f, 0xbb, 0x94,
	0x9b, 0x7e, 0x5f, 0x33, 0xdb, 0xbe, 0x59, 0x48, 0xbd, 0xba, 0x3b, 0x18, 0x91, 0xf3, 0x59, 0xa1,
	0x6d, 0x51, 0xe4, 0x21, 0x6c, 0xc8, 0x34, 0x2a, 0xa6, 0xff, 0xdf, 0x3a, 0x6d, 0x1f, 0x38, 0x18,
	0xf9, 0x9b, 0x11, 0x45, 0x25, 0x49, 0xf9, 0x2b, 0x7f, 0xb7, 0xba, 0xa1, 0xee, 0x68, 0x16, 0xd7,
	0x86, 0xa7, 0x3a, 0xfd, 0xa6, 0x1e, 0x75, 0x59, 0x9d, 0xc2, 0x26, 0xab, 0xb9, 0xcd, 0xc1, 0xd4,
	0x29, 0x51, 0x6a, 0x96, 0x53, 0xa7, 0xbf, 0x70, 0xa2, 0x4e, 0x44, 0x39, 0x16, 0x6d, 0x70, 0x06,
	0x5b, 0x2c, 0xaf, 0x33, 0xaf, 0x8a, 0x39, 0x16, 0x38, 0x36, 0x48, 0x69, 0x64, 0xde, 0x90, 0x6f,
	0x1d, 0x51, 0x8e, 0x6d, 0xa4, 0x6e, 0x53, 0xc4, 0x42, 0x1a, 0x2d, 0xb2, 0xe2, 0xcb, 0x3c, 0xe3,
	0x41, 0x5c, 0x45, 0x66, 0x5c, 0x61, 0x0d, 0x7f, 0xee, 0xb2, 0xce, 0x1e, 0x60, 0xdd, 0x18, 0x6f,
	0x6f, 0xf9, 0x70, 0x55, 0x46, 0xa5, 0x96, 0x52, 0xe7, 0xff, 0x3e, 0x68, 0x29, 0x8c, 0xfb, 0x7a,
	0x1c, 0xba, 0x93, 0x88, 0xa9, 0x96, 0x39, 0x02, 0xc3, 0x26, 0x27, 0x74, 0xd6, 0xc6, 0x81, 0xe5,
	0xe6, 0xce, 0x5c, 0x22, 0x77, 0xeb, 0xf9, 0xc7, 0x07, 0xf9, 0x72, 0xcd, 0xd0, 0xa3, 0x4e, 0x3f,
	0x80, 0x41, 0x22, 0x27, 0x8e, 0xe0, 0x33, 0xeb, 0xfd, 0xbe, 0x1e, 0x04, 0x6f, 0xab, 0xa4, 0x59,
	0x34, 0x4f, 0x6e, 0x0a, 0xec, 0xfe, 0x91, 0xef, 0xbf, 0x4d, 0xd7, 0xe0, 0xcc, 0x1b, 0x2c, 0x8c,
	0xbb, 0x17, 0x77, 0x5f, 0x6e, 0x93, 0x31, 0x50, 0x4a, 0x3e, 0xf9, 0xc1, 0x15, 0x19, 0xc7, 0x19,
	0xfd, 0xb3, 0x56, 0x5e, 0xf9, 0xf9, 0xdd, 0xc9, 0x77, 0x54, 0x4e, 0xbe, 0x52, 0xd5, 0xff, 0x11,
	0xbe, 0x2d, 0xc7, 0x75, 0x9d, 0x35, 0x36, 0xff, 0xd9, 0x19, 0xf8, 0x37, 0xf0, 0xa4, 0x5b, 0xdd,
	0xd0, 0x98, 0xd7, 0xd2, 0xd2, 0x7f, 0xb3, 0xad, 0x64, 0x8a, 0xaa, 0xcb, 0x9c, 0xb0, 0xd7, 0xd8,
	0xb1, 0xfd, 0x3b, 0x0b, 0x65, 0x83, 0x42, 0x1e, 0xf2, 0x5c, 0x5f, 0x2a, 0x5b, 0x7e, 0x0a, 0xfc,
	0x2f, 0x00, 0x00, 0xff, 0xff, 0x8f, 0x0e, 0x35, 0xf2, 0x38, 0x16, 0x00, 0x00,
}
