// Code generated by protoc-gen-go. DO NOT EDIT.
// source: niuniu_logic_msg.proto

package net

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// -------------牛牛游戏消息---------------------------------------
// 游戏状态
type MsgNiuniuGameInfoFreeRep struct {
	TimeLeave        *uint32 `protobuf:"varint,1,opt,name=time_leave" json:"time_leave,omitempty"`
	BankerId         *uint32 `protobuf:"varint,2,opt,name=banker_id" json:"banker_id,omitempty"`
	CurPrivateRound  *uint32 `protobuf:"varint,3,opt,name=cur_private_round" json:"cur_private_round,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgNiuniuGameInfoFreeRep) Reset()                    { *m = MsgNiuniuGameInfoFreeRep{} }
func (m *MsgNiuniuGameInfoFreeRep) String() string            { return proto.CompactTextString(m) }
func (*MsgNiuniuGameInfoFreeRep) ProtoMessage()               {}
func (*MsgNiuniuGameInfoFreeRep) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{0} }

func (m *MsgNiuniuGameInfoFreeRep) GetTimeLeave() uint32 {
	if m != nil && m.TimeLeave != nil {
		return *m.TimeLeave
	}
	return 0
}

func (m *MsgNiuniuGameInfoFreeRep) GetBankerId() uint32 {
	if m != nil && m.BankerId != nil {
		return *m.BankerId
	}
	return 0
}

func (m *MsgNiuniuGameInfoFreeRep) GetCurPrivateRound() uint32 {
	if m != nil && m.CurPrivateRound != nil {
		return *m.CurPrivateRound
	}
	return 0
}

type MsgNiuniuGameInfoPlayRep struct {
	AllJettonScore   []int64     `protobuf:"varint,1,rep,name=all_jetton_score" json:"all_jetton_score,omitempty"`
	TableCards       []*MsgCards `protobuf:"bytes,2,rep,name=table_cards" json:"table_cards,omitempty"`
	BankerId         *uint32     `protobuf:"varint,3,opt,name=banker_id" json:"banker_id,omitempty"`
	GameStatus       *uint32     `protobuf:"varint,4,opt,name=game_status" json:"game_status,omitempty"`
	ShowCards        []uint32    `protobuf:"varint,5,rep,name=show_cards" json:"show_cards,omitempty"`
	PlayerStatus     []uint32    `protobuf:"varint,6,rep,name=player_status" json:"player_status,omitempty"`
	TimeLeave        *uint32     `protobuf:"varint,7,opt,name=time_leave" json:"time_leave,omitempty"`
	ApplyList        []uint32    `protobuf:"varint,8,rep,name=apply_list" json:"apply_list,omitempty"`
	TurnMaxScore     []int64     `protobuf:"varint,9,rep,name=turn_max_score" json:"turn_max_score,omitempty"`
	CurPrivateRound  *uint32     `protobuf:"varint,10,opt,name=cur_private_round" json:"cur_private_round,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *MsgNiuniuGameInfoPlayRep) Reset()                    { *m = MsgNiuniuGameInfoPlayRep{} }
func (m *MsgNiuniuGameInfoPlayRep) String() string            { return proto.CompactTextString(m) }
func (*MsgNiuniuGameInfoPlayRep) ProtoMessage()               {}
func (*MsgNiuniuGameInfoPlayRep) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{1} }

func (m *MsgNiuniuGameInfoPlayRep) GetAllJettonScore() []int64 {
	if m != nil {
		return m.AllJettonScore
	}
	return nil
}

func (m *MsgNiuniuGameInfoPlayRep) GetTableCards() []*MsgCards {
	if m != nil {
		return m.TableCards
	}
	return nil
}

func (m *MsgNiuniuGameInfoPlayRep) GetBankerId() uint32 {
	if m != nil && m.BankerId != nil {
		return *m.BankerId
	}
	return 0
}

func (m *MsgNiuniuGameInfoPlayRep) GetGameStatus() uint32 {
	if m != nil && m.GameStatus != nil {
		return *m.GameStatus
	}
	return 0
}

func (m *MsgNiuniuGameInfoPlayRep) GetShowCards() []uint32 {
	if m != nil {
		return m.ShowCards
	}
	return nil
}

func (m *MsgNiuniuGameInfoPlayRep) GetPlayerStatus() []uint32 {
	if m != nil {
		return m.PlayerStatus
	}
	return nil
}

func (m *MsgNiuniuGameInfoPlayRep) GetTimeLeave() uint32 {
	if m != nil && m.TimeLeave != nil {
		return *m.TimeLeave
	}
	return 0
}

func (m *MsgNiuniuGameInfoPlayRep) GetApplyList() []uint32 {
	if m != nil {
		return m.ApplyList
	}
	return nil
}

func (m *MsgNiuniuGameInfoPlayRep) GetTurnMaxScore() []int64 {
	if m != nil {
		return m.TurnMaxScore
	}
	return nil
}

func (m *MsgNiuniuGameInfoPlayRep) GetCurPrivateRound() uint32 {
	if m != nil && m.CurPrivateRound != nil {
		return *m.CurPrivateRound
	}
	return 0
}

// 游戏开始
type MsgNiuniuStartRep struct {
	CurPrivateRound  *uint32 `protobuf:"varint,1,opt,name=cur_private_round" json:"cur_private_round,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgNiuniuStartRep) Reset()                    { *m = MsgNiuniuStartRep{} }
func (m *MsgNiuniuStartRep) String() string            { return proto.CompactTextString(m) }
func (*MsgNiuniuStartRep) ProtoMessage()               {}
func (*MsgNiuniuStartRep) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{2} }

func (m *MsgNiuniuStartRep) GetCurPrivateRound() uint32 {
	if m != nil && m.CurPrivateRound != nil {
		return *m.CurPrivateRound
	}
	return 0
}

// 申请庄家
type MsgNiuniuApplyBanker struct {
	Score            *uint32 `protobuf:"varint,1,opt,name=score" json:"score,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgNiuniuApplyBanker) Reset()                    { *m = MsgNiuniuApplyBanker{} }
func (m *MsgNiuniuApplyBanker) String() string            { return proto.CompactTextString(m) }
func (*MsgNiuniuApplyBanker) ProtoMessage()               {}
func (*MsgNiuniuApplyBanker) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{3} }

func (m *MsgNiuniuApplyBanker) GetScore() uint32 {
	if m != nil && m.Score != nil {
		return *m.Score
	}
	return 0
}

type MsgNiuniuApplyBankerRep struct {
	Chairid          *uint32 `protobuf:"varint,1,opt,name=chairid" json:"chairid,omitempty"`
	Score            *uint32 `protobuf:"varint,2,opt,name=score" json:"score,omitempty"`
	Result           *uint32 `protobuf:"varint,3,opt,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgNiuniuApplyBankerRep) Reset()                    { *m = MsgNiuniuApplyBankerRep{} }
func (m *MsgNiuniuApplyBankerRep) String() string            { return proto.CompactTextString(m) }
func (*MsgNiuniuApplyBankerRep) ProtoMessage()               {}
func (*MsgNiuniuApplyBankerRep) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{4} }

func (m *MsgNiuniuApplyBankerRep) GetChairid() uint32 {
	if m != nil && m.Chairid != nil {
		return *m.Chairid
	}
	return 0
}

func (m *MsgNiuniuApplyBankerRep) GetScore() uint32 {
	if m != nil && m.Score != nil {
		return *m.Score
	}
	return 0
}

func (m *MsgNiuniuApplyBankerRep) GetResult() uint32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

type MsgNiuniuBankerResultRep struct {
	BankerId         *uint32  `protobuf:"varint,1,opt,name=banker_id" json:"banker_id,omitempty"`
	ApplyList        []uint32 `protobuf:"varint,2,rep,name=apply_list" json:"apply_list,omitempty"`
	TurnMaxScore     []int64  `protobuf:"varint,3,rep,name=turn_max_score" json:"turn_max_score,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *MsgNiuniuBankerResultRep) Reset()                    { *m = MsgNiuniuBankerResultRep{} }
func (m *MsgNiuniuBankerResultRep) String() string            { return proto.CompactTextString(m) }
func (*MsgNiuniuBankerResultRep) ProtoMessage()               {}
func (*MsgNiuniuBankerResultRep) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{5} }

func (m *MsgNiuniuBankerResultRep) GetBankerId() uint32 {
	if m != nil && m.BankerId != nil {
		return *m.BankerId
	}
	return 0
}

func (m *MsgNiuniuBankerResultRep) GetApplyList() []uint32 {
	if m != nil {
		return m.ApplyList
	}
	return nil
}

func (m *MsgNiuniuBankerResultRep) GetTurnMaxScore() []int64 {
	if m != nil {
		return m.TurnMaxScore
	}
	return nil
}

// 用户下注
type MsgNiuniuPlaceJettonReq struct {
	JettonScore      *int64 `protobuf:"varint,1,opt,name=jetton_score" json:"jetton_score,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgNiuniuPlaceJettonReq) Reset()                    { *m = MsgNiuniuPlaceJettonReq{} }
func (m *MsgNiuniuPlaceJettonReq) String() string            { return proto.CompactTextString(m) }
func (*MsgNiuniuPlaceJettonReq) ProtoMessage()               {}
func (*MsgNiuniuPlaceJettonReq) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{6} }

func (m *MsgNiuniuPlaceJettonReq) GetJettonScore() int64 {
	if m != nil && m.JettonScore != nil {
		return *m.JettonScore
	}
	return 0
}

type MsgNiuniuPlaceJettonRep struct {
	JettonScore      *int64  `protobuf:"varint,1,opt,name=jetton_score" json:"jetton_score,omitempty"`
	Result           *uint32 `protobuf:"varint,2,opt,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgNiuniuPlaceJettonRep) Reset()                    { *m = MsgNiuniuPlaceJettonRep{} }
func (m *MsgNiuniuPlaceJettonRep) String() string            { return proto.CompactTextString(m) }
func (*MsgNiuniuPlaceJettonRep) ProtoMessage()               {}
func (*MsgNiuniuPlaceJettonRep) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{7} }

func (m *MsgNiuniuPlaceJettonRep) GetJettonScore() int64 {
	if m != nil && m.JettonScore != nil {
		return *m.JettonScore
	}
	return 0
}

func (m *MsgNiuniuPlaceJettonRep) GetResult() uint32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

type MsgNiuniuPlaceJettonBroadcast struct {
	Chairid          *uint32 `protobuf:"varint,1,opt,name=chairid" json:"chairid,omitempty"`
	JettonScore      *int64  `protobuf:"varint,2,opt,name=jetton_score" json:"jetton_score,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgNiuniuPlaceJettonBroadcast) Reset()                    { *m = MsgNiuniuPlaceJettonBroadcast{} }
func (m *MsgNiuniuPlaceJettonBroadcast) String() string            { return proto.CompactTextString(m) }
func (*MsgNiuniuPlaceJettonBroadcast) ProtoMessage()               {}
func (*MsgNiuniuPlaceJettonBroadcast) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{8} }

func (m *MsgNiuniuPlaceJettonBroadcast) GetChairid() uint32 {
	if m != nil && m.Chairid != nil {
		return *m.Chairid
	}
	return 0
}

func (m *MsgNiuniuPlaceJettonBroadcast) GetJettonScore() int64 {
	if m != nil && m.JettonScore != nil {
		return *m.JettonScore
	}
	return 0
}

// 发牌
type MsgNiuniuSendCardRep struct {
	Cards            []uint32 `protobuf:"varint,1,rep,name=cards" json:"cards,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *MsgNiuniuSendCardRep) Reset()                    { *m = MsgNiuniuSendCardRep{} }
func (m *MsgNiuniuSendCardRep) String() string            { return proto.CompactTextString(m) }
func (*MsgNiuniuSendCardRep) ProtoMessage()               {}
func (*MsgNiuniuSendCardRep) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{9} }

func (m *MsgNiuniuSendCardRep) GetCards() []uint32 {
	if m != nil {
		return m.Cards
	}
	return nil
}

// 摆牌
type MsgNiuniuChangeCard struct {
	Cards            []uint32 `protobuf:"varint,1,rep,name=cards" json:"cards,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *MsgNiuniuChangeCard) Reset()                    { *m = MsgNiuniuChangeCard{} }
func (m *MsgNiuniuChangeCard) String() string            { return proto.CompactTextString(m) }
func (*MsgNiuniuChangeCard) ProtoMessage()               {}
func (*MsgNiuniuChangeCard) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{10} }

func (m *MsgNiuniuChangeCard) GetCards() []uint32 {
	if m != nil {
		return m.Cards
	}
	return nil
}

type MsgNiuniuChangeCardRep struct {
	OperId           *uint32  `protobuf:"varint,1,opt,name=oper_id" json:"oper_id,omitempty"`
	Result           *uint32  `protobuf:"varint,2,opt,name=result" json:"result,omitempty"`
	Cards            []uint32 `protobuf:"varint,3,rep,name=cards" json:"cards,omitempty"`
	CardType         *uint32  `protobuf:"varint,4,opt,name=card_type" json:"card_type,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *MsgNiuniuChangeCardRep) Reset()                    { *m = MsgNiuniuChangeCardRep{} }
func (m *MsgNiuniuChangeCardRep) String() string            { return proto.CompactTextString(m) }
func (*MsgNiuniuChangeCardRep) ProtoMessage()               {}
func (*MsgNiuniuChangeCardRep) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{11} }

func (m *MsgNiuniuChangeCardRep) GetOperId() uint32 {
	if m != nil && m.OperId != nil {
		return *m.OperId
	}
	return 0
}

func (m *MsgNiuniuChangeCardRep) GetResult() uint32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *MsgNiuniuChangeCardRep) GetCards() []uint32 {
	if m != nil {
		return m.Cards
	}
	return nil
}

func (m *MsgNiuniuChangeCardRep) GetCardType() uint32 {
	if m != nil && m.CardType != nil {
		return *m.CardType
	}
	return 0
}

// 游戏结束
type MsgNiuniuGameEnd struct {
	TimeLeave        *uint32     `protobuf:"varint,1,opt,name=time_leave" json:"time_leave,omitempty"`
	TableCards       []*MsgCards `protobuf:"bytes,2,rep,name=table_cards" json:"table_cards,omitempty"`
	CardTypes        []uint32    `protobuf:"varint,3,rep,name=card_types" json:"card_types,omitempty"`
	PlayerScore      []int64     `protobuf:"varint,4,rep,name=player_score" json:"player_score,omitempty"`
	WinMultiple      []int32     `protobuf:"varint,5,rep,name=win_multiple" json:"win_multiple,omitempty"`
	CurPrivateRound  *uint32     `protobuf:"varint,6,opt,name=cur_private_round" json:"cur_private_round,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *MsgNiuniuGameEnd) Reset()                    { *m = MsgNiuniuGameEnd{} }
func (m *MsgNiuniuGameEnd) String() string            { return proto.CompactTextString(m) }
func (*MsgNiuniuGameEnd) ProtoMessage()               {}
func (*MsgNiuniuGameEnd) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{12} }

func (m *MsgNiuniuGameEnd) GetTimeLeave() uint32 {
	if m != nil && m.TimeLeave != nil {
		return *m.TimeLeave
	}
	return 0
}

func (m *MsgNiuniuGameEnd) GetTableCards() []*MsgCards {
	if m != nil {
		return m.TableCards
	}
	return nil
}

func (m *MsgNiuniuGameEnd) GetCardTypes() []uint32 {
	if m != nil {
		return m.CardTypes
	}
	return nil
}

func (m *MsgNiuniuGameEnd) GetPlayerScore() []int64 {
	if m != nil {
		return m.PlayerScore
	}
	return nil
}

func (m *MsgNiuniuGameEnd) GetWinMultiple() []int32 {
	if m != nil {
		return m.WinMultiple
	}
	return nil
}

func (m *MsgNiuniuGameEnd) GetCurPrivateRound() uint32 {
	if m != nil && m.CurPrivateRound != nil {
		return *m.CurPrivateRound
	}
	return 0
}

func init() {
	proto.RegisterType((*MsgNiuniuGameInfoFreeRep)(nil), "net.msg_niuniu_game_info_free_rep")
	proto.RegisterType((*MsgNiuniuGameInfoPlayRep)(nil), "net.msg_niuniu_game_info_play_rep")
	proto.RegisterType((*MsgNiuniuStartRep)(nil), "net.msg_niuniu_start_rep")
	proto.RegisterType((*MsgNiuniuApplyBanker)(nil), "net.msg_niuniu_apply_banker")
	proto.RegisterType((*MsgNiuniuApplyBankerRep)(nil), "net.msg_niuniu_apply_banker_rep")
	proto.RegisterType((*MsgNiuniuBankerResultRep)(nil), "net.msg_niuniu_banker_result_rep")
	proto.RegisterType((*MsgNiuniuPlaceJettonReq)(nil), "net.msg_niuniu_place_jetton_req")
	proto.RegisterType((*MsgNiuniuPlaceJettonRep)(nil), "net.msg_niuniu_place_jetton_rep")
	proto.RegisterType((*MsgNiuniuPlaceJettonBroadcast)(nil), "net.msg_niuniu_place_jetton_broadcast")
	proto.RegisterType((*MsgNiuniuSendCardRep)(nil), "net.msg_niuniu_send_card_rep")
	proto.RegisterType((*MsgNiuniuChangeCard)(nil), "net.msg_niuniu_change_card")
	proto.RegisterType((*MsgNiuniuChangeCardRep)(nil), "net.msg_niuniu_change_card_rep")
	proto.RegisterType((*MsgNiuniuGameEnd)(nil), "net.msg_niuniu_game_end")
}

func init() { proto.RegisterFile("niuniu_logic_msg.proto", fileDescriptor13) }

var fileDescriptor13 = []byte{
	// 533 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x53, 0x51, 0x72, 0xd3, 0x30,
	0x10, 0x9d, 0xc4, 0x4d, 0x4b, 0x37, 0x71, 0x68, 0xdc, 0x34, 0x98, 0x00, 0x33, 0xc1, 0x7c, 0x60,
	0x7e, 0x32, 0x03, 0x1c, 0x81, 0x3f, 0x66, 0x38, 0x02, 0xa3, 0x51, 0xec, 0x6d, 0x22, 0x50, 0x24,
	0x21, 0xc9, 0x2d, 0xb9, 0x03, 0x17, 0xe1, 0x96, 0x8c, 0xd6, 0x71, 0xeb, 0x04, 0x87, 0xe1, 0x77,
	0xf5, 0xf6, 0xbd, 0xb7, 0x4f, 0xbb, 0x30, 0x53, 0xa2, 0x52, 0xa2, 0x62, 0x52, 0xaf, 0x45, 0xc1,
	0xb6, 0x6e, 0xbd, 0x34, 0x56, 0x7b, 0x9d, 0x44, 0x0a, 0xfd, 0xfc, 0x66, 0xc5, 0x1d, 0x86, 0x22,
	0x73, 0xde, 0x56, 0x85, 0xaf, 0xdf, 0xe6, 0x57, 0x68, 0xad, 0xb6, 0xac, 0xd0, 0x25, 0xd6, 0x95,
	0x8c, 0xc3, 0xab, 0x80, 0xda, 0x73, 0xad, 0xf9, 0x16, 0x99, 0x50, 0xb7, 0x9a, 0xdd, 0x5a, 0x44,
	0x66, 0xd1, 0x24, 0x09, 0x80, 0x17, 0x5b, 0x64, 0x12, 0xf9, 0x1d, 0xa6, 0xbd, 0x45, 0x2f, 0x8f,
	0x93, 0x09, 0x5c, 0xae, 0xb8, 0xfa, 0x8e, 0x96, 0x89, 0x32, 0xed, 0x53, 0xe9, 0x39, 0x4c, 0x8a,
	0xca, 0x32, 0x63, 0xc5, 0x1d, 0xf7, 0xc8, 0xac, 0xae, 0x54, 0x99, 0x46, 0xe1, 0x29, 0xfb, 0xd5,
	0x3f, 0xa1, 0x61, 0x24, 0xdf, 0x91, 0x46, 0x0a, 0x57, 0x5c, 0x4a, 0xf6, 0x0d, 0xbd, 0xd7, 0x8a,
	0xb9, 0x42, 0xdb, 0xa0, 0x14, 0xe5, 0x51, 0xf2, 0x06, 0x86, 0x9e, 0xaf, 0x24, 0xb2, 0x82, 0xdb,
	0xd2, 0xa5, 0xfd, 0x45, 0x94, 0x0f, 0x3f, 0x8c, 0x97, 0x0a, 0xfd, 0x32, 0x50, 0x52, 0xf5, 0xd0,
	0x0e, 0x69, 0x26, 0xd7, 0x30, 0x24, 0x1d, 0xe7, 0xb9, 0xaf, 0x5c, 0x7a, 0x46, 0xc5, 0x04, 0xc0,
	0x6d, 0xf4, 0xfd, 0x9e, 0x6b, 0xb0, 0x88, 0xf2, 0x38, 0xb9, 0x81, 0x38, 0xd8, 0x40, 0xdb, 0x40,
	0xcf, 0xa9, 0x7c, 0x38, 0xf5, 0x45, 0xd3, 0xce, 0x8d, 0x91, 0x3b, 0x26, 0x85, 0xf3, 0xe9, 0x13,
	0xc2, 0xcd, 0x60, 0xec, 0x2b, 0xab, 0xd8, 0x96, 0xff, 0xdc, 0xfb, 0xbe, 0x24, 0xdf, 0x9d, 0x71,
	0x00, 0xc5, 0xf1, 0x1e, 0xa6, 0xad, 0x34, 0x9c, 0xe7, 0xd6, 0x53, 0x08, 0x9d, 0x2d, 0x94, 0x77,
	0x96, 0xc3, 0xb3, 0x56, 0x4b, 0x6d, 0xa2, 0x9e, 0x38, 0x89, 0x61, 0xd0, 0xe4, 0x15, 0x90, 0x5f,
	0xe0, 0xc5, 0x09, 0x24, 0x69, 0x3c, 0x85, 0x8b, 0x62, 0xc3, 0x85, 0x15, 0x7b, 0xe6, 0xc7, 0xf6,
	0xfa, 0x17, 0xc7, 0x70, 0x6e, 0xd1, 0x55, 0xd2, 0xef, 0xbf, 0xee, 0x2b, 0xbc, 0x6c, 0xd1, 0x3d,
	0x10, 0x05, 0x04, 0xf1, 0x1d, 0x24, 0xdf, 0xeb, 0x48, 0xa9, 0x7f, 0x22, 0xa5, 0x28, 0xa4, 0x94,
	0x7d, 0x3c, 0x70, 0x6b, 0x24, 0x2f, 0xb0, 0x59, 0x02, 0x8b, 0x3f, 0x92, 0x29, 0x8c, 0x8e, 0x56,
	0xa2, 0x97, 0x47, 0xd9, 0xa7, 0x7f, 0x35, 0x99, 0xee, 0xa6, 0xd6, 0x60, 0x34, 0x68, 0xf6, 0x19,
	0x5e, 0x9f, 0x22, 0x59, 0x59, 0xcd, 0xcb, 0x82, 0x3b, 0xff, 0x77, 0x5a, 0xc7, 0xdc, 0x7d, 0x32,
	0xf4, 0x0e, 0xd2, 0xf6, 0x87, 0xa2, 0x2a, 0x69, 0xc3, 0xc8, 0x4d, 0x0c, 0x83, 0x7a, 0xdb, 0xc2,
	0x3a, 0xc7, 0xd9, 0x5b, 0x98, 0xb5, 0xa0, 0xc5, 0x86, 0xab, 0x75, 0xbd, 0xda, 0xc7, 0x40, 0x06,
	0xf3, 0x6e, 0x60, 0xf3, 0x8d, 0xda, 0xb4, 0x43, 0x3f, 0x1a, 0xef, 0x91, 0x2d, 0xa2, 0xfc, 0x27,
	0x70, 0x49, 0xbd, 0x7e, 0x67, 0xb0, 0xbe, 0x85, 0xec, 0x77, 0x0f, 0xae, 0x8f, 0x8f, 0x12, 0x55,
	0xd9, 0x79, 0xee, 0xff, 0x75, 0x84, 0x09, 0xc0, 0x83, 0x46, 0xa3, 0x3b, 0x85, 0x51, 0x73, 0x5c,
	0x94, 0xd7, 0x19, 0xdd, 0xc6, 0x14, 0x46, 0xf7, 0x42, 0xb1, 0x6d, 0x25, 0xbd, 0x30, 0x12, 0xe9,
	0x10, 0x07, 0xdd, 0xeb, 0x7f, 0x1e, 0xf4, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0xa1, 0x10, 0xa6,
	0x28, 0xea, 0x04, 0x00, 0x00,
}
