// Code generated by protoc-gen-go. DO NOT EDIT.
// source: paijiu_logic_msg.proto

package net

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// 游戏状态
type MsgPaijiuGameInfoFreeRep struct {
	TimeLeave        *uint32 `protobuf:"varint,1,opt,name=time_leave" json:"time_leave,omitempty"`
	BankerId         *uint32 `protobuf:"varint,2,opt,name=banker_id" json:"banker_id,omitempty"`
	BankerTime       *uint32 `protobuf:"varint,3,opt,name=banker_time" json:"banker_time,omitempty"`
	BankerWinScore   *int64  `protobuf:"varint,4,opt,name=banker_win_score" json:"banker_win_score,omitempty"`
	BankerScore      *int64  `protobuf:"varint,5,opt,name=banker_score" json:"banker_score,omitempty"`
	BankerBuyinScore *int64  `protobuf:"varint,6,opt,name=banker_buyin_score" json:"banker_buyin_score,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgPaijiuGameInfoFreeRep) Reset()                    { *m = MsgPaijiuGameInfoFreeRep{} }
func (m *MsgPaijiuGameInfoFreeRep) String() string            { return proto.CompactTextString(m) }
func (*MsgPaijiuGameInfoFreeRep) ProtoMessage()               {}
func (*MsgPaijiuGameInfoFreeRep) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{0} }

func (m *MsgPaijiuGameInfoFreeRep) GetTimeLeave() uint32 {
	if m != nil && m.TimeLeave != nil {
		return *m.TimeLeave
	}
	return 0
}

func (m *MsgPaijiuGameInfoFreeRep) GetBankerId() uint32 {
	if m != nil && m.BankerId != nil {
		return *m.BankerId
	}
	return 0
}

func (m *MsgPaijiuGameInfoFreeRep) GetBankerTime() uint32 {
	if m != nil && m.BankerTime != nil {
		return *m.BankerTime
	}
	return 0
}

func (m *MsgPaijiuGameInfoFreeRep) GetBankerWinScore() int64 {
	if m != nil && m.BankerWinScore != nil {
		return *m.BankerWinScore
	}
	return 0
}

func (m *MsgPaijiuGameInfoFreeRep) GetBankerScore() int64 {
	if m != nil && m.BankerScore != nil {
		return *m.BankerScore
	}
	return 0
}

func (m *MsgPaijiuGameInfoFreeRep) GetBankerBuyinScore() int64 {
	if m != nil && m.BankerBuyinScore != nil {
		return *m.BankerBuyinScore
	}
	return 0
}

type MsgPaijiuGameInfoPlayRep struct {
	AllJettonScore   []int64     `protobuf:"varint,1,rep,name=all_jetton_score" json:"all_jetton_score,omitempty"`
	TableCards       []*MsgCards `protobuf:"bytes,2,rep,name=table_cards" json:"table_cards,omitempty"`
	BankerId         *uint32     `protobuf:"varint,3,opt,name=banker_id" json:"banker_id,omitempty"`
	BankerTime       *uint32     `protobuf:"varint,4,opt,name=banker_time" json:"banker_time,omitempty"`
	BankerWinScore   *int64      `protobuf:"varint,5,opt,name=banker_win_score" json:"banker_win_score,omitempty"`
	BankerScore      *int64      `protobuf:"varint,6,opt,name=banker_score" json:"banker_score,omitempty"`
	TimeLeave        *uint32     `protobuf:"varint,7,opt,name=time_leave" json:"time_leave,omitempty"`
	GameStatus       *uint32     `protobuf:"varint,8,opt,name=game_status" json:"game_status,omitempty"`
	SelfJettonScore  []int64     `protobuf:"varint,9,rep,name=self_jetton_score" json:"self_jetton_score,omitempty"`
	BankerBuyinScore *int64      `protobuf:"varint,10,opt,name=banker_buyin_score" json:"banker_buyin_score,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *MsgPaijiuGameInfoPlayRep) Reset()                    { *m = MsgPaijiuGameInfoPlayRep{} }
func (m *MsgPaijiuGameInfoPlayRep) String() string            { return proto.CompactTextString(m) }
func (*MsgPaijiuGameInfoPlayRep) ProtoMessage()               {}
func (*MsgPaijiuGameInfoPlayRep) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{1} }

func (m *MsgPaijiuGameInfoPlayRep) GetAllJettonScore() []int64 {
	if m != nil {
		return m.AllJettonScore
	}
	return nil
}

func (m *MsgPaijiuGameInfoPlayRep) GetTableCards() []*MsgCards {
	if m != nil {
		return m.TableCards
	}
	return nil
}

func (m *MsgPaijiuGameInfoPlayRep) GetBankerId() uint32 {
	if m != nil && m.BankerId != nil {
		return *m.BankerId
	}
	return 0
}

func (m *MsgPaijiuGameInfoPlayRep) GetBankerTime() uint32 {
	if m != nil && m.BankerTime != nil {
		return *m.BankerTime
	}
	return 0
}

func (m *MsgPaijiuGameInfoPlayRep) GetBankerWinScore() int64 {
	if m != nil && m.BankerWinScore != nil {
		return *m.BankerWinScore
	}
	return 0
}

func (m *MsgPaijiuGameInfoPlayRep) GetBankerScore() int64 {
	if m != nil && m.BankerScore != nil {
		return *m.BankerScore
	}
	return 0
}

func (m *MsgPaijiuGameInfoPlayRep) GetTimeLeave() uint32 {
	if m != nil && m.TimeLeave != nil {
		return *m.TimeLeave
	}
	return 0
}

func (m *MsgPaijiuGameInfoPlayRep) GetGameStatus() uint32 {
	if m != nil && m.GameStatus != nil {
		return *m.GameStatus
	}
	return 0
}

func (m *MsgPaijiuGameInfoPlayRep) GetSelfJettonScore() []int64 {
	if m != nil {
		return m.SelfJettonScore
	}
	return nil
}

func (m *MsgPaijiuGameInfoPlayRep) GetBankerBuyinScore() int64 {
	if m != nil && m.BankerBuyinScore != nil {
		return *m.BankerBuyinScore
	}
	return 0
}

// 游戏开始
type MsgPaijiuStartRep struct {
	BankerId         *uint32 `protobuf:"varint,1,opt,name=banker_id" json:"banker_id,omitempty"`
	BankerScore      *int64  `protobuf:"varint,2,opt,name=banker_score" json:"banker_score,omitempty"`
	TimeLeave        *uint32 `protobuf:"varint,3,opt,name=time_leave" json:"time_leave,omitempty"`
	BankerBuyinScore *int64  `protobuf:"varint,4,opt,name=banker_buyin_score" json:"banker_buyin_score,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgPaijiuStartRep) Reset()                    { *m = MsgPaijiuStartRep{} }
func (m *MsgPaijiuStartRep) String() string            { return proto.CompactTextString(m) }
func (*MsgPaijiuStartRep) ProtoMessage()               {}
func (*MsgPaijiuStartRep) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{2} }

func (m *MsgPaijiuStartRep) GetBankerId() uint32 {
	if m != nil && m.BankerId != nil {
		return *m.BankerId
	}
	return 0
}

func (m *MsgPaijiuStartRep) GetBankerScore() int64 {
	if m != nil && m.BankerScore != nil {
		return *m.BankerScore
	}
	return 0
}

func (m *MsgPaijiuStartRep) GetTimeLeave() uint32 {
	if m != nil && m.TimeLeave != nil {
		return *m.TimeLeave
	}
	return 0
}

func (m *MsgPaijiuStartRep) GetBankerBuyinScore() int64 {
	if m != nil && m.BankerBuyinScore != nil {
		return *m.BankerBuyinScore
	}
	return 0
}

// 用户下注
type MsgPaijiuPlaceJettonReq struct {
	JettonArea       *uint32 `protobuf:"varint,1,opt,name=jetton_area" json:"jetton_area,omitempty"`
	JettonScore      *int64  `protobuf:"varint,2,opt,name=jetton_score" json:"jetton_score,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgPaijiuPlaceJettonReq) Reset()                    { *m = MsgPaijiuPlaceJettonReq{} }
func (m *MsgPaijiuPlaceJettonReq) String() string            { return proto.CompactTextString(m) }
func (*MsgPaijiuPlaceJettonReq) ProtoMessage()               {}
func (*MsgPaijiuPlaceJettonReq) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{3} }

func (m *MsgPaijiuPlaceJettonReq) GetJettonArea() uint32 {
	if m != nil && m.JettonArea != nil {
		return *m.JettonArea
	}
	return 0
}

func (m *MsgPaijiuPlaceJettonReq) GetJettonScore() int64 {
	if m != nil && m.JettonScore != nil {
		return *m.JettonScore
	}
	return 0
}

type MsgPaijiuPlaceJettonRep struct {
	JettonArea       *uint32 `protobuf:"varint,1,opt,name=jetton_area" json:"jetton_area,omitempty"`
	JettonScore      *int64  `protobuf:"varint,2,opt,name=jetton_score" json:"jetton_score,omitempty"`
	Result           *uint32 `protobuf:"varint,3,opt,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgPaijiuPlaceJettonRep) Reset()                    { *m = MsgPaijiuPlaceJettonRep{} }
func (m *MsgPaijiuPlaceJettonRep) String() string            { return proto.CompactTextString(m) }
func (*MsgPaijiuPlaceJettonRep) ProtoMessage()               {}
func (*MsgPaijiuPlaceJettonRep) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{4} }

func (m *MsgPaijiuPlaceJettonRep) GetJettonArea() uint32 {
	if m != nil && m.JettonArea != nil {
		return *m.JettonArea
	}
	return 0
}

func (m *MsgPaijiuPlaceJettonRep) GetJettonScore() int64 {
	if m != nil && m.JettonScore != nil {
		return *m.JettonScore
	}
	return 0
}

func (m *MsgPaijiuPlaceJettonRep) GetResult() uint32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

type MsgPaijiuPlaceJettonBroadcast struct {
	Uid              *uint32 `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	JettonArea       *uint32 `protobuf:"varint,2,opt,name=jetton_area" json:"jetton_area,omitempty"`
	JettonScore      *int64  `protobuf:"varint,3,opt,name=jetton_score" json:"jetton_score,omitempty"`
	TotalJettonScore *int64  `protobuf:"varint,4,opt,name=total_jetton_score" json:"total_jetton_score,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgPaijiuPlaceJettonBroadcast) Reset()                    { *m = MsgPaijiuPlaceJettonBroadcast{} }
func (m *MsgPaijiuPlaceJettonBroadcast) String() string            { return proto.CompactTextString(m) }
func (*MsgPaijiuPlaceJettonBroadcast) ProtoMessage()               {}
func (*MsgPaijiuPlaceJettonBroadcast) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{5} }

func (m *MsgPaijiuPlaceJettonBroadcast) GetUid() uint32 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *MsgPaijiuPlaceJettonBroadcast) GetJettonArea() uint32 {
	if m != nil && m.JettonArea != nil {
		return *m.JettonArea
	}
	return 0
}

func (m *MsgPaijiuPlaceJettonBroadcast) GetJettonScore() int64 {
	if m != nil && m.JettonScore != nil {
		return *m.JettonScore
	}
	return 0
}

func (m *MsgPaijiuPlaceJettonBroadcast) GetTotalJettonScore() int64 {
	if m != nil && m.TotalJettonScore != nil {
		return *m.TotalJettonScore
	}
	return 0
}

// 游戏结束
type MsgPaijiuGameEnd struct {
	TimeLeave        *uint32     `protobuf:"varint,1,opt,name=time_leave" json:"time_leave,omitempty"`
	TableCards       []*MsgCards `protobuf:"bytes,2,rep,name=table_cards" json:"table_cards,omitempty"`
	CardTypes        []uint32    `protobuf:"varint,3,rep,name=card_types" json:"card_types,omitempty"`
	BankerWinScore   *int64      `protobuf:"varint,4,opt,name=banker_win_score" json:"banker_win_score,omitempty"`
	BankerTotalScore *int64      `protobuf:"varint,5,opt,name=banker_total_score" json:"banker_total_score,omitempty"`
	BankerTime       *uint32     `protobuf:"varint,6,opt,name=banker_time" json:"banker_time,omitempty"`
	UserScore        *int64      `protobuf:"varint,7,opt,name=user_score" json:"user_score,omitempty"`
	PlayerScore      []int64     `protobuf:"varint,8,rep,name=player_score" json:"player_score,omitempty"`
	WinMultiple      []int32     `protobuf:"varint,9,rep,name=win_multiple" json:"win_multiple,omitempty"`
	RandCard         *uint32     `protobuf:"varint,10,opt,name=rand_card" json:"rand_card,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *MsgPaijiuGameEnd) Reset()                    { *m = MsgPaijiuGameEnd{} }
func (m *MsgPaijiuGameEnd) String() string            { return proto.CompactTextString(m) }
func (*MsgPaijiuGameEnd) ProtoMessage()               {}
func (*MsgPaijiuGameEnd) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{6} }

func (m *MsgPaijiuGameEnd) GetTimeLeave() uint32 {
	if m != nil && m.TimeLeave != nil {
		return *m.TimeLeave
	}
	return 0
}

func (m *MsgPaijiuGameEnd) GetTableCards() []*MsgCards {
	if m != nil {
		return m.TableCards
	}
	return nil
}

func (m *MsgPaijiuGameEnd) GetCardTypes() []uint32 {
	if m != nil {
		return m.CardTypes
	}
	return nil
}

func (m *MsgPaijiuGameEnd) GetBankerWinScore() int64 {
	if m != nil && m.BankerWinScore != nil {
		return *m.BankerWinScore
	}
	return 0
}

func (m *MsgPaijiuGameEnd) GetBankerTotalScore() int64 {
	if m != nil && m.BankerTotalScore != nil {
		return *m.BankerTotalScore
	}
	return 0
}

func (m *MsgPaijiuGameEnd) GetBankerTime() uint32 {
	if m != nil && m.BankerTime != nil {
		return *m.BankerTime
	}
	return 0
}

func (m *MsgPaijiuGameEnd) GetUserScore() int64 {
	if m != nil && m.UserScore != nil {
		return *m.UserScore
	}
	return 0
}

func (m *MsgPaijiuGameEnd) GetPlayerScore() []int64 {
	if m != nil {
		return m.PlayerScore
	}
	return nil
}

func (m *MsgPaijiuGameEnd) GetWinMultiple() []int32 {
	if m != nil {
		return m.WinMultiple
	}
	return nil
}

func (m *MsgPaijiuGameEnd) GetRandCard() uint32 {
	if m != nil && m.RandCard != nil {
		return *m.RandCard
	}
	return 0
}

// 申请庄家
type MsgPaijiuApplyBanker struct {
	ApplyOper        *uint32 `protobuf:"varint,1,opt,name=apply_oper" json:"apply_oper,omitempty"`
	ApplyScore       *int64  `protobuf:"varint,2,opt,name=apply_score" json:"apply_score,omitempty"`
	AutoAddscore     *uint32 `protobuf:"varint,3,opt,name=auto_addscore" json:"auto_addscore,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgPaijiuApplyBanker) Reset()                    { *m = MsgPaijiuApplyBanker{} }
func (m *MsgPaijiuApplyBanker) String() string            { return proto.CompactTextString(m) }
func (*MsgPaijiuApplyBanker) ProtoMessage()               {}
func (*MsgPaijiuApplyBanker) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{7} }

func (m *MsgPaijiuApplyBanker) GetApplyOper() uint32 {
	if m != nil && m.ApplyOper != nil {
		return *m.ApplyOper
	}
	return 0
}

func (m *MsgPaijiuApplyBanker) GetApplyScore() int64 {
	if m != nil && m.ApplyScore != nil {
		return *m.ApplyScore
	}
	return 0
}

func (m *MsgPaijiuApplyBanker) GetAutoAddscore() uint32 {
	if m != nil && m.AutoAddscore != nil {
		return *m.AutoAddscore
	}
	return 0
}

type MsgPaijiuApplyBankerRep struct {
	ApplyOper        *uint32 `protobuf:"varint,1,opt,name=apply_oper" json:"apply_oper,omitempty"`
	Result           *uint32 `protobuf:"varint,2,opt,name=result" json:"result,omitempty"`
	BuyinScore       *int64  `protobuf:"varint,3,opt,name=buyin_score" json:"buyin_score,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgPaijiuApplyBankerRep) Reset()                    { *m = MsgPaijiuApplyBankerRep{} }
func (m *MsgPaijiuApplyBankerRep) String() string            { return proto.CompactTextString(m) }
func (*MsgPaijiuApplyBankerRep) ProtoMessage()               {}
func (*MsgPaijiuApplyBankerRep) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{8} }

func (m *MsgPaijiuApplyBankerRep) GetApplyOper() uint32 {
	if m != nil && m.ApplyOper != nil {
		return *m.ApplyOper
	}
	return 0
}

func (m *MsgPaijiuApplyBankerRep) GetResult() uint32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *MsgPaijiuApplyBankerRep) GetBuyinScore() int64 {
	if m != nil && m.BuyinScore != nil {
		return *m.BuyinScore
	}
	return 0
}

// 切换庄家
type MsgPaijiuChangeBanker struct {
	BankerUser       *uint32 `protobuf:"varint,1,opt,name=banker_user" json:"banker_user,omitempty"`
	BankerScore      *int64  `protobuf:"varint,2,opt,name=banker_score" json:"banker_score,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgPaijiuChangeBanker) Reset()                    { *m = MsgPaijiuChangeBanker{} }
func (m *MsgPaijiuChangeBanker) String() string            { return proto.CompactTextString(m) }
func (*MsgPaijiuChangeBanker) ProtoMessage()               {}
func (*MsgPaijiuChangeBanker) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{9} }

func (m *MsgPaijiuChangeBanker) GetBankerUser() uint32 {
	if m != nil && m.BankerUser != nil {
		return *m.BankerUser
	}
	return 0
}

func (m *MsgPaijiuChangeBanker) GetBankerScore() int64 {
	if m != nil && m.BankerScore != nil {
		return *m.BankerScore
	}
	return 0
}

// 更新积分
type MsgPaijiuChangeUserScore struct {
	ChairId          *uint32 `protobuf:"varint,1,opt,name=chair_id" json:"chair_id,omitempty"`
	Score            *int64  `protobuf:"varint,2,opt,name=score" json:"score,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgPaijiuChangeUserScore) Reset()                    { *m = MsgPaijiuChangeUserScore{} }
func (m *MsgPaijiuChangeUserScore) String() string            { return proto.CompactTextString(m) }
func (*MsgPaijiuChangeUserScore) ProtoMessage()               {}
func (*MsgPaijiuChangeUserScore) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{10} }

func (m *MsgPaijiuChangeUserScore) GetChairId() uint32 {
	if m != nil && m.ChairId != nil {
		return *m.ChairId
	}
	return 0
}

func (m *MsgPaijiuChangeUserScore) GetScore() int64 {
	if m != nil && m.Score != nil {
		return *m.Score
	}
	return 0
}

// 申请庄家列表
type MsgPaijiuApplyList struct {
	PlayerIds        []uint32 `protobuf:"varint,1,rep,name=player_ids" json:"player_ids,omitempty"`
	ApplyScore       []int64  `protobuf:"varint,2,rep,name=apply_score" json:"apply_score,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *MsgPaijiuApplyList) Reset()                    { *m = MsgPaijiuApplyList{} }
func (m *MsgPaijiuApplyList) String() string            { return proto.CompactTextString(m) }
func (*MsgPaijiuApplyList) ProtoMessage()               {}
func (*MsgPaijiuApplyList) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{11} }

func (m *MsgPaijiuApplyList) GetPlayerIds() []uint32 {
	if m != nil {
		return m.PlayerIds
	}
	return nil
}

func (m *MsgPaijiuApplyList) GetApplyScore() []int64 {
	if m != nil {
		return m.ApplyScore
	}
	return nil
}

// 插队
type MsgPaijiuJumpApplyQueueReq struct {
	JumpPos          *uint32 `protobuf:"varint,1,opt,name=jump_pos" json:"jump_pos,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgPaijiuJumpApplyQueueReq) Reset()                    { *m = MsgPaijiuJumpApplyQueueReq{} }
func (m *MsgPaijiuJumpApplyQueueReq) String() string            { return proto.CompactTextString(m) }
func (*MsgPaijiuJumpApplyQueueReq) ProtoMessage()               {}
func (*MsgPaijiuJumpApplyQueueReq) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{12} }

func (m *MsgPaijiuJumpApplyQueueReq) GetJumpPos() uint32 {
	if m != nil && m.JumpPos != nil {
		return *m.JumpPos
	}
	return 0
}

type MsgPaijiuJumpApplyQueueRep struct {
	Result           *uint32 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgPaijiuJumpApplyQueueRep) Reset()                    { *m = MsgPaijiuJumpApplyQueueRep{} }
func (m *MsgPaijiuJumpApplyQueueRep) String() string            { return proto.CompactTextString(m) }
func (*MsgPaijiuJumpApplyQueueRep) ProtoMessage()               {}
func (*MsgPaijiuJumpApplyQueueRep) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{13} }

func (m *MsgPaijiuJumpApplyQueueRep) GetResult() uint32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

// 	庄家结算
type MsgPaijiuBankerCalcRep struct {
	BankerTime       *uint32 `protobuf:"varint,1,opt,name=banker_time" json:"banker_time,omitempty"`
	WinCount         *uint32 `protobuf:"varint,2,opt,name=win_count" json:"win_count,omitempty"`
	BuyinScore       *int64  `protobuf:"varint,3,opt,name=buyin_score" json:"buyin_score,omitempty"`
	WinScore         *int64  `protobuf:"varint,4,opt,name=win_score" json:"win_score,omitempty"`
	WinMax           *int64  `protobuf:"varint,5,opt,name=win_max" json:"win_max,omitempty"`
	WinMin           *int64  `protobuf:"varint,6,opt,name=win_min" json:"win_min,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgPaijiuBankerCalcRep) Reset()                    { *m = MsgPaijiuBankerCalcRep{} }
func (m *MsgPaijiuBankerCalcRep) String() string            { return proto.CompactTextString(m) }
func (*MsgPaijiuBankerCalcRep) ProtoMessage()               {}
func (*MsgPaijiuBankerCalcRep) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{14} }

func (m *MsgPaijiuBankerCalcRep) GetBankerTime() uint32 {
	if m != nil && m.BankerTime != nil {
		return *m.BankerTime
	}
	return 0
}

func (m *MsgPaijiuBankerCalcRep) GetWinCount() uint32 {
	if m != nil && m.WinCount != nil {
		return *m.WinCount
	}
	return 0
}

func (m *MsgPaijiuBankerCalcRep) GetBuyinScore() int64 {
	if m != nil && m.BuyinScore != nil {
		return *m.BuyinScore
	}
	return 0
}

func (m *MsgPaijiuBankerCalcRep) GetWinScore() int64 {
	if m != nil && m.WinScore != nil {
		return *m.WinScore
	}
	return 0
}

func (m *MsgPaijiuBankerCalcRep) GetWinMax() int64 {
	if m != nil && m.WinMax != nil {
		return *m.WinMax
	}
	return 0
}

func (m *MsgPaijiuBankerCalcRep) GetWinMin() int64 {
	if m != nil && m.WinMin != nil {
		return *m.WinMin
	}
	return 0
}

//  庄家补币
type MsgPaijiuAddBankerscoreRep struct {
	BuyinScore       *int64 `protobuf:"varint,1,opt,name=buyin_score" json:"buyin_score,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgPaijiuAddBankerscoreRep) Reset()                    { *m = MsgPaijiuAddBankerscoreRep{} }
func (m *MsgPaijiuAddBankerscoreRep) String() string            { return proto.CompactTextString(m) }
func (*MsgPaijiuAddBankerscoreRep) ProtoMessage()               {}
func (*MsgPaijiuAddBankerscoreRep) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{15} }

func (m *MsgPaijiuAddBankerscoreRep) GetBuyinScore() int64 {
	if m != nil && m.BuyinScore != nil {
		return *m.BuyinScore
	}
	return 0
}

func init() {
	proto.RegisterType((*MsgPaijiuGameInfoFreeRep)(nil), "net.msg_paijiu_game_info_free_rep")
	proto.RegisterType((*MsgPaijiuGameInfoPlayRep)(nil), "net.msg_paijiu_game_info_play_rep")
	proto.RegisterType((*MsgPaijiuStartRep)(nil), "net.msg_paijiu_start_rep")
	proto.RegisterType((*MsgPaijiuPlaceJettonReq)(nil), "net.msg_paijiu_place_jetton_req")
	proto.RegisterType((*MsgPaijiuPlaceJettonRep)(nil), "net.msg_paijiu_place_jetton_rep")
	proto.RegisterType((*MsgPaijiuPlaceJettonBroadcast)(nil), "net.msg_paijiu_place_jetton_broadcast")
	proto.RegisterType((*MsgPaijiuGameEnd)(nil), "net.msg_paijiu_game_end")
	proto.RegisterType((*MsgPaijiuApplyBanker)(nil), "net.msg_paijiu_apply_banker")
	proto.RegisterType((*MsgPaijiuApplyBankerRep)(nil), "net.msg_paijiu_apply_banker_rep")
	proto.RegisterType((*MsgPaijiuChangeBanker)(nil), "net.msg_paijiu_change_banker")
	proto.RegisterType((*MsgPaijiuChangeUserScore)(nil), "net.msg_paijiu_change_user_score")
	proto.RegisterType((*MsgPaijiuApplyList)(nil), "net.msg_paijiu_apply_list")
	proto.RegisterType((*MsgPaijiuJumpApplyQueueReq)(nil), "net.msg_paijiu_jump_apply_queue_req")
	proto.RegisterType((*MsgPaijiuJumpApplyQueueRep)(nil), "net.msg_paijiu_jump_apply_queue_rep")
	proto.RegisterType((*MsgPaijiuBankerCalcRep)(nil), "net.msg_paijiu_banker_calc_rep")
	proto.RegisterType((*MsgPaijiuAddBankerscoreRep)(nil), "net.msg_paijiu_add_bankerscore_rep")
}

func init() { proto.RegisterFile("paijiu_logic_msg.proto", fileDescriptor4) }

var fileDescriptor4 = []byte{
	// 685 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x55, 0xcd, 0x72, 0xd3, 0x3c,
	0x14, 0x9d, 0x44, 0x4d, 0x9b, 0xde, 0x34, 0xfd, 0x52, 0xb7, 0xfd, 0x30, 0xe1, 0x2f, 0x98, 0x4d,
	0x56, 0x9d, 0x01, 0x86, 0x35, 0x6c, 0x98, 0xe1, 0x09, 0x18, 0x58, 0x69, 0x14, 0xfb, 0x36, 0x75,
	0x51, 0x2c, 0x55, 0x92, 0x29, 0xd9, 0xf1, 0x04, 0x2c, 0x79, 0x05, 0x5e, 0x93, 0x91, 0x64, 0xc7,
	0x8a, 0xeb, 0x06, 0xd8, 0x25, 0xc7, 0xd6, 0xb9, 0xe7, 0x9e, 0x7b, 0xae, 0x0c, 0xff, 0x4b, 0x96,
	0x5f, 0xe7, 0x25, 0xe5, 0x62, 0x99, 0xa7, 0x74, 0xa5, 0x97, 0x17, 0x52, 0x09, 0x23, 0x22, 0x52,
	0xa0, 0x99, 0x9e, 0x2f, 0x98, 0x46, 0x0b, 0x52, 0x6d, 0x54, 0x99, 0x1a, 0xff, 0x6c, 0x3a, 0x41,
	0xa5, 0x84, 0xa2, 0xa9, 0xc8, 0xd0, 0x23, 0xc9, 0xaf, 0x1e, 0x3c, 0xb1, 0xaf, 0x55, 0x64, 0x4b,
	0xb6, 0x42, 0x9a, 0x17, 0x97, 0x82, 0x5e, 0x2a, 0x44, 0xaa, 0x50, 0x46, 0x11, 0x80, 0xc9, 0x57,
	0x48, 0x39, 0xb2, 0xaf, 0x18, 0xf7, 0x66, 0xbd, 0xf9, 0x38, 0x3a, 0x81, 0xc3, 0x05, 0x2b, 0xbe,
	0xa0, 0xa2, 0x79, 0x16, 0xf7, 0x1d, 0x74, 0x0a, 0xa3, 0x0a, 0xb2, 0x6f, 0xc7, 0xc4, 0x81, 0x31,
	0x4c, 0x2a, 0xf0, 0x36, 0x2f, 0xa8, 0x4e, 0x85, 0xc2, 0x78, 0x6f, 0xd6, 0x9b, 0x93, 0xe8, 0x0c,
	0x8e, 0xaa, 0x27, 0x1e, 0x1d, 0x38, 0x74, 0x0a, 0x51, 0x85, 0x2e, 0xca, 0xf5, 0xe6, 0xc4, 0xbe,
	0x7d, 0x96, 0xfc, 0xec, 0xdf, 0xa3, 0x54, 0x72, 0xb6, 0x76, 0x4a, 0x63, 0x98, 0x30, 0xce, 0xe9,
	0x35, 0x1a, 0x23, 0xea, 0xb3, 0xbd, 0x19, 0x99, 0x93, 0xe8, 0x05, 0x8c, 0x0c, 0x5b, 0x70, 0xa4,
	0x29, 0x53, 0x99, 0x8e, 0xfb, 0x33, 0x32, 0x1f, 0xbd, 0x3a, 0xbe, 0x28, 0xd0, 0x5c, 0x58, 0x4a,
	0x87, 0x6e, 0x37, 0x45, 0xba, 0x9a, 0xda, 0xbb, 0xb7, 0xa9, 0x41, 0x67, 0x53, 0x4e, 0x78, 0xcb,
	0xc0, 0x83, 0x9a, 0xd8, 0x35, 0xa0, 0x0d, 0x33, 0xa5, 0x8e, 0x87, 0x0e, 0x7c, 0x08, 0x27, 0x1a,
	0xf9, 0xe5, 0x76, 0x03, 0x87, 0xae, 0x81, 0x6e, 0x63, 0xc0, 0x19, 0x23, 0xe0, 0x2c, 0xf0, 0x45,
	0x1b, 0xa6, 0x8c, 0xb3, 0x63, 0xab, 0x1f, 0x3f, 0xb7, 0xb6, 0xc0, 0x7e, 0x87, 0x40, 0xdf, 0x79,
	0x77, 0x41, 0x37, 0xbb, 0xe4, 0x03, 0x3c, 0x0a, 0x0a, 0x4a, 0xce, 0x52, 0xac, 0x35, 0x2b, 0xbc,
	0xb1, 0xbd, 0x55, 0xff, 0x98, 0x42, 0xd6, 0x54, 0xde, 0x6a, 0xcb, 0x55, 0x4e, 0x3e, 0xed, 0x62,
	0x92, 0xff, 0xc0, 0x14, 0x1d, 0xc3, 0xbe, 0x42, 0x5d, 0x72, 0xe3, 0xf5, 0x27, 0xb7, 0xf0, 0xfc,
	0x3e, 0xe6, 0x85, 0x12, 0x2c, 0x4b, 0x99, 0x36, 0xd1, 0x08, 0x48, 0xb9, 0xf1, 0xa6, 0x55, 0xac,
	0xdf, 0x59, 0x8c, 0xd4, 0x31, 0x35, 0xc2, 0xb0, 0x56, 0xd4, 0xbc, 0x39, 0xdf, 0xfb, 0x70, 0xda,
	0x8e, 0x29, 0x16, 0x59, 0xe7, 0x1a, 0xfd, 0x55, 0x2c, 0x23, 0x00, 0xfb, 0x83, 0x9a, 0xb5, 0x44,
	0x1d, 0x93, 0x19, 0xd9, 0xb9, 0x57, 0xcd, 0xdc, 0xbc, 0xc2, 0x30, 0x9e, 0xad, 0x34, 0xef, 0x3b,
	0x0d, 0x11, 0x40, 0xa9, 0x37, 0x81, 0x38, 0xa8, 0x73, 0x6c, 0x97, 0x6a, 0x83, 0x0e, 0x5d, 0x06,
	0xcf, 0xe0, 0xc8, 0x56, 0x5b, 0x95, 0xdc, 0xe4, 0x92, 0xfb, 0x64, 0x0e, 0x6c, 0xca, 0x14, 0x2b,
	0x32, 0x27, 0xd6, 0x05, 0x72, 0x9c, 0x7c, 0x86, 0x07, 0x81, 0x03, 0x4c, 0x4a, 0xbe, 0xa6, 0xbe,
	0xb0, 0xad, 0xe6, 0xff, 0x0b, 0x89, 0xaa, 0x31, 0xde, 0x63, 0xe1, 0x3c, 0xcf, 0x61, 0xcc, 0x4a,
	0x23, 0x28, 0xcb, 0xb2, 0xc6, 0xf9, 0x71, 0xf2, 0x71, 0x2b, 0x30, 0x21, 0x75, 0x7d, 0x57, 0xdd,
	0xa1, 0x6f, 0x92, 0xd1, 0x5c, 0x54, 0x41, 0xa4, 0xdd, 0x44, 0x93, 0xf7, 0x10, 0x07, 0xbc, 0xe9,
	0x15, 0x2b, 0x96, 0x58, 0x6b, 0x6e, 0x6c, 0xb3, 0x46, 0xed, 0xda, 0xa4, 0xe4, 0x2d, 0x3c, 0xbe,
	0x4b, 0xd3, 0xd8, 0x1b, 0x4d, 0x60, 0x98, 0x5e, 0xb1, 0x3c, 0xd8, 0xc8, 0x31, 0x0c, 0x42, 0x82,
	0x77, 0x70, 0x7e, 0xa7, 0x3f, 0x9e, 0x6b, 0x63, 0x3b, 0xab, 0x46, 0x92, 0x67, 0xda, 0xdd, 0x6a,
	0x1d, 0xc6, 0x91, 0x39, 0x49, 0x5e, 0xc3, 0xb3, 0x80, 0xe1, 0xba, 0x5c, 0xc9, 0x8a, 0xe6, 0xa6,
	0xc4, 0x12, 0xdd, 0x82, 0x4e, 0x60, 0xe8, 0x70, 0x29, 0xb4, 0x57, 0x91, 0xbc, 0xfc, 0xd3, 0x21,
	0x19, 0xd8, 0xe8, 0x8f, 0xfc, 0xe8, 0xc1, 0x34, 0x38, 0x53, 0x99, 0x91, 0x32, 0x9e, 0xd6, 0xab,
	0x1b, 0x66, 0x6d, 0xf3, 0xd9, 0xb0, 0x09, 0x4a, 0x45, 0x59, 0xec, 0x9a, 0x46, 0xfd, 0x5e, 0x98,
	0xeb, 0xff, 0xe0, 0xc0, 0x85, 0x8f, 0x7d, 0xab, 0xc2, 0x5c, 0x03, 0x79, 0x51, 0x7d, 0x1f, 0xde,
	0xc0, 0xd3, 0xd0, 0xba, 0x2c, 0xab, 0x34, 0x39, 0x96, 0x8d, 0xa6, 0xa0, 0x96, 0xd5, 0x44, 0x7e,
	0x07, 0x00, 0x00, 0xff, 0xff, 0x8e, 0x11, 0x5d, 0x02, 0x47, 0x07, 0x00, 0x00,
}
